### ISSUE TITLE
/nick jkariotisIE9 results in Cannot implicitly convert type 'System.Collections.Generic.Dictionary' to 'string'

### ISSUE THREAD

**Issue by jasonkar** [JabbR/JabbR#10]
[problem description]
Can't change nickname by typing command /nick jkariotisIE9

[repro steps]
1. type command /nick jkariotisIE
2. type command /join jkariotis
3. type /leave
4. type /nick jkariotisIE9

expected results:
My nickname should change

actual results:
Cannot implicitly convert type 'System.Collections.Generic.Dictionary' to 'string'

**Comment by davidfowl** [comment]
Worked for me. Where did you see that exception? Are you debugging the app? Do you have first chance exception turned on?

**Comment by jasonkar** [comment]
Hi David,

I got this playing around on http://chatapp.apphb.com/. I've attached a
screen shot.

Let me know if you have any other questions or if I can be of assistance.

-j

**Comment by davidfowl** [comment]
You got this where? Did you look at elmah or did you get it in the firebug? Where did you get the exception?

**Comment by jasonkar** [comment]
I got this in the client, not server-side. Just in the plain browser, not
doing any sniffing or other inspection. Did you get the screenshot?

-j

**Comment by davidfowl** [comment]
Don't see any screenshot

**Comment by jasonkar** [comment]
I've attached it to this email again. If it is being stripped off I can send
it to an alternate address if you'd like or put it up on DropBox or
something else.

-j

**Comment by davidfowl** [comment]
I can't see any attachments. Does github support email attachments?

**Comment by jasonkar** [comment]
It doesn't appear to.

I sent you an invitation to a shared dropbox folder. The screenshot is
untitled.png.

-j

**Comment by davidfowl** [comment]
Where did you send the invitation?

**Comment by jasonkar** [comment]
To the github link. Do you have a direct email address?

-j
On Aug 31, 2011 8:08 PM, "davidfowl" <
reply@reply.github.com>
wrote:

**Comment by davidfowl** [comment]
Is it possible for you to log into github and put the error message in here?

**Comment by davidfowl** [comment]
I got a repro :)

**Comment by davidfowl** [comment]
What browser are you using.

**Comment by jasonkar** [comment]
Hi David,

I was using IE9. Glad to hear that you got a repro. Let me know if I can
help with anything else.

-Jason

**Comment by davidfowl** [comment]
Fixed

**Comment by jasonkar** [comment]
Excellent, thanks for taking the time to dig in and get a fix.

-Jason
