### ISSUE TITLE
Add support for local blob storage

### ISSUE THREAD

**Issue by ElanHasson** [JabbR/JabbR#1023]
Currently JabbR only supports blob storage via Windows Azure.

Adding support for writing attachments to local (or UNC) paths would allow for deployments that do not leverage Windows Azure Blob storage but rather more traditional means of serving static content (CDNs with Origin Server).
- I have updated the work done for #1015 to support the Local storage option in the status page ![jabbr - status](https://f.cloud.github.com/assets/234704/1294568/71368ece-3086-11e3-98c7-100746bb1489.png)
- Updated the Administration page to reflect the new configuration values (LocalBlobStoragePath and LocalBlobStorageUriPrefix) ![jabbr - administration page](https://f.cloud.github.com/assets/234704/1294554/f4ef9554-3085-11e3-9297-d0fca6d7ed0a.png)
- Added several string resources in LanguageResources.resx to support the  Administration page additions 

Here is a screenshot of it in action: 
![jabbr](https://f.cloud.github.com/assets/234704/1294572/8c768d9c-3086-11e3-8806-8c01f1b7ce43.png)

**Comment by cmaish** [comment]
Merged

**Comment by ElanHasson** [comment]
Updated install script from http://about.jabbr.net/self-host-install.html can be found at https://gist.github.com/ElanHasson/6919005

I didn't see the site in the repository, if there is a "more correct" place to put this, let me know. Also I'll update the "less easy method" if you show me where to put the files.
