### ISSUE TITLE
Have a way to see what rooms a user is in

### ISSUE THREAD

**Issue by haacked** [JabbR/JabbR#103]
When I enter the lobby, I'm typically looking for someone specific, such as dfowler. I'd like the ability to see what rooms he's in.

Maybe something like:

```
/rooms @dfowler
```

And when I'm in a room, I'd like to be able to hover over a name and also see that.

**Comment by kiliman** [comment]
Actually there already is a command for that.

`/who @nickname`

I think we're planning on adding more user info, things like Last Activity, Away Message, etc.

**Comment by haacked** [comment]
Thanks!
