### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by slamj1** [JabbR/JabbR#1037]
Master Branch won't compile under VS.NET 2012 Update 3. NuGet Packages out of sync. Specifically - EntityFramework, Microsoft.OWin. They are targeting old Alpha versions. Running Build.cmd does not help.

**Comment by cmaish** [comment]
Building from the dev branch or using the binaries (from http://about.jabbr.net/) is the way to go at the moment (the 'stable' binary is built from master).  We should be updating readme.md to indicate this soon.

Unfortunately, the nightlies of the ASP.NET WebStack from Microsoft are removed after a little while, so the dependencies used to build master aren't always available unless you already have them locally.

**Comment by slamj1** [comment]
Understood and thanks!
