### ISSUE TITLE
Provide option to beep when browser is not in focus and a new message comes up

### ISSUE THREAD

**Issue by haacked** [JabbR/JabbR#104]
Basically, do the IM style beep.

**Comment by kiliman** [comment]
I'll add that as well as pinned browser support with a new message notification icon.

**Comment by davidfowl** [comment]
@kiliman, make it so that the user can turn it off with a setting and store it in the jabbr state cookie.

**Comment by ajryan** [comment]
I just submitted a pull request with Chrome notifications.

**Comment by haacked** [comment]
I don't see the pull request.

**Comment by davidfowl** [comment]
It's live here http://jabbr-staging.apphb.com/#/rooms/newfeatures

**Comment by haacked** [comment]
It should be a simple toggle on the room itself. Like how the Windows audio speaker icon toggles.

**Comment by davidfowl** [comment]
This is in
