### ISSUE TITLE
Kicking is broken after 1st kick

### ISSUE THREAD

**Issue by Yantrio** [JabbR/JabbR#1047]
1. kick person,
2. person re-joins
3. kick person again (fails)

we would love to fix this asap :)

**Comment by adamralph** [comment]
+1 loads of spammers on recently

**Comment by cmaish** [comment]
This is related to the user-in-room cache which is maintained on each WFE individually.  We need some sort of communication between servers to handle cache invalidation... if only there were some real-time cross-machine communication library that we could use.

**Comment by cmaish** [comment]
Note this is also the cause of users sometimes not appearing in the userlist correctly (ie appearing as offline etc)
