### ISSUE TITLE
Add Search of transcripts

### ISSUE THREAD

**Issue by haacked** [JabbR/JabbR#105]
I want to be able to search the transcripts for a room. Rooms should have the ability to turn this on or off when creating the room. That way, a room for shooting the breeze isn't a permanent record of your tasteless jokes, but a room used for a team working together has a searchable archive.

**Comment by kiliman** [comment]
I like the transcripts used in SO chat, so I hope we "steal" some of their ideas :P

**Comment by half-ogre** [comment]
I started working on transcripts like what Campfire does. I'll take a look at SO chat, too.

**Comment by davidfowl** [comment]
IT's time to start working on this.

**Comment by half-ogre** [comment]
Lucene for the index? Have a UI in mind?

**Comment by davidfowl** [comment]
Right now all I have is the ability to download messages in a json format over a specified time range (not even for private rooms). 

I'm still looking for good UI suggestions.

**Comment by haacked** [comment]
After two years, Imma assume this ain't happening. :smile:

**Comment by davidfowl** [comment]
@Haacked slacker

**Comment by samandmoore** [comment]
i was really close to finishing this, but i got too busy to finish. there is a PR in there somewhere that got it close to production ready.

**Comment by davidfowl** [comment]
@samandmoore slacker.
