### ISSUE TITLE
Build fails to deploy for master branch

### ISSUE THREAD

**Issue by jschell** [JabbR/JabbR#1050]
> Related issue: https://github.com/JabbR/JabbR/issues/987

From commit: 475d327a230f0ac9e88525f326436d8d2bafc20d
    @davidfowl  2013-11-24 01:15:59 -08:00

Deploy on 2013-11-26 21:11 -08:00
    Status: Pass

Deploy on 2013-11-30 ~09:00-onwards -08:00
    Status: Fail
### Cause:

MyGet packages for SignalR and WebApi listed in build have expired and are no longer available
### Workaround:

Search and replace the following pairs

webapi 
    was:    5.1.0-alpha1-131015
    now:    5.1.0-rc1-131128 

signalr
    was:    2.1.0-pre-131015-b246
    now:    2.1.0-pre-131021-b252 

Also, rename files 'Scripts\jquery.signalR-$oldVersion.js' and ''Scripts\jquery.signalR-$oldVersion.min.js' to 'Scripts\jquery.signalR-$currentVersion.js', 'Scripts\jquery.signalR-$currentVersion.min.js'
### Proposed Solutions:
1. Create a 'stable' branch that uses packages that will be available for at least the lifetime of the commit.
2. Implement CI solution to update the resources as new nightly builds are shipped.

**Comment by davidfowl** [comment]
I think jabbr will have it's own myget feed.

**Comment by davidfowl** [comment]
Ok this should be fixed now. I put up a myget feed that has the versions of the dependencies that jabbr is using (that can go away).
