### ISSUE TITLE
build.cmd tests break.

### ISSUE THREAD

**Issue by cmaish** [JabbR/JabbR#1073]
[https://jabbrlive.blob.core.windows.net/jabbr-uploads/build_eb21.png](https://jabbrlive.blob.core.windows.net/jabbr-uploads/build_eb21.png)

Resharper testrunner runs the tests fine.  Some people's machines run the test fine.  Build works.

**Comment by DamianEdwards** [comment]
Getting this on my machine too

**Comment by cmaish** [comment]
From [Application Compatibility in the .NET Framework 4.5](http://msdn.microsoft.com/en-us/library/hh367887%28v=vs.110%29.aspx), this is something changed between .net 4 and 4.5:

| Feature | Change | Impact |
| --- | --- | --- |
| Uri.EscapeDataString , Uri.EscapeUriString, and Uri.UnescapeDataString | The list of reserved and unreserved characters now supports RFC 3986. | Specific changes: |
|  |  | Unreserved escaped characters are un-escaped. |
|  |  | EscapeDataString escapes reserved characters based on RFC 3986. |
|  |  | EscapeUriString does not escape reserved characters. |
|  |  | UnescapeDataString does not throw an exception if it encounters an invalid escape sequence. |

Unreserved characters changed:

(in 2386) unreserved  = alphanum | "-" | "_" | "." | "!" | "~" | "*" | "'" | "(" | ")"
(in 3986) unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"

As such, "!" will be encoded but only on .net 4.5+. causing the test to fail when it's run on 4.0 or lower (ie windows 7 in the command prompt?).  This has no impact on upboat.me's output, so I'm thinking I'll just remove that bit of the test.
