### ISSUE TITLE
Private rooms are visible to others via /who

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#1082]
When typing /who @username in JabbR it lists private rooms owned by the user as well as public rooms. This seems to be undesired behavior.

**Comment by Buildstarted** [comment]
Other users who have access to the private room can see them as well. Otherwise they don't see it.

**Comment by cmaish** [comment]
I think that's desired behaviour.  If you're a member of the (private) room, you should be able to know who its owners are

**Comment by Buildstarted** [comment]
Yeah, which is why i closed it. I commented stating what the actual behavior was :)
