### ISSUE TITLE
Need instructions on how to set country/flag on Accounts settings page

### ISSUE THREAD

**Issue by KirillOsenkov** [JabbR/JabbR#1092]
On the account settings page, if your country is not set, it displays a dash. It isn't clickable and there's no indication on how to change it.

Add a label on the account settings page that says "To change your country, type /flag XX where XX is the country code". Or just add a combobox/textbox there with a list of supported countries.

**Comment by hnrkndrssn** [comment]
This will be added in the next release of JabbR.net
