### ISSUE TITLE
CSRF token not validated

### ISSUE THREAD

**Issue by cmaish** [JabbR/JabbR#1093]
Signin page (among others) has a CSRF token embedded in the form (Html.AntiForgeryToken) but it's never checked.  We should probably call ValidateCsrfToken somewhere.

**Comment by cmaish** [comment]
@davidfowl mentioned in #meta that we could look at sniffing the useragent to see if the user's running a browser instead of (or in addition to) using the sec- header.  I don't think that this is viable (as an unidentified/lesser used browser then winds up having no CSRF protection).  Does anyone have any ideas?

**Comment by davidfowl** [comment]
It's specifically looking for signalr .net clients

**Comment by cmaish** [comment]
Oh ok, so skip it if useragent contains signalr... sounds good to me.
