### ISSUE TITLE
Twitter Content Provider is not working anymore

### ISSUE THREAD

**Issue by hnrkndrssn** [JabbR/JabbR#1107]
The TweetContentProvider was deleted (by accident?) in the following commit https://github.com/JabbR/JabbR/commit/8dc76924450cb0e7c422acdd3c64490c104adf70

It needs to be restored.

**Comment by hnrkndrssn** [comment]
Source commit where content providers were removed, https://github.com/JabbR/JabbR/commit/362ed4d16327c72aee24c41fd3844fe7eb5663b3 

Not sure if there was a reason why those 8 content providers were removed...

**Comment by daanl** [comment]
https://github.com/JabbR/JabbR/pull/1108

**Comment by hnrkndrssn** [comment]
#1109 merged
