### ISSUE TITLE
Cancel Google OAuth login shows wrong error message

### ISSUE THREAD

**Issue by stimpy77** [JabbR/JabbR#1116]
If you cancel logging in via Google OAuth, the error message is "Index (zero based) must be greater than or equal to zero and less than the size of the argument list."

**Comment by cmaish** [comment]
This looks like it's an issue with SimpleAuthentication (which isn't fixed by updating to the newest version).  When google authentication is backed-out-of, IAuthenticationCallbackProvider's Process method is called with this error.

**Comment by hnrkndrssn** [comment]
Ping @PureKrome

Sent from my Windows Phone

**Comment by cmaish** [comment]
https://github.com/SimpleAuthentication/SimpleAuthentication/issues/146 created

**Comment by cmaish** [comment]
https://github.com/SimpleAuthentication/SimpleAuthentication/pull/147 created, just need to wait for the SimpleAuthentication change to get into a build to pull it into JabbR.

**Comment by PureKrome** [comment]
Ok. new packages are up on NuGet.org.

You should be updating to [v SimpleAuthentication 0.3.14](http://www.nuget.org/packages/SimpleAuthentication.Core/).
