### ISSUE TITLE
Shouldn't kick tell someone (or everyone) they've been kicked?

### ISSUE THREAD

**Issue by cmaish** [JabbR/JabbR#1122]
Maybe other room participants?  This is what it looks like to others when you get kicked:

![clipboard_e534](https://cloud.githubusercontent.com/assets/1271535/3121904/ec0b2ae2-e760-11e3-956f-541072a184d7.png)

**Comment by Buildstarted** [comment]
A reason should be required as well `/kick cjm1 reason goes here` so that a log is kept as to why a room owner kicked a particular person.

**Comment by cmaish** [comment]
In dev
