### ISSUE TITLE
Basic markdown support for messages

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#1124]
Allow some basic markdown support for things like **bold** _italic_ and `inline code`

**Comment by khellang** [comment]
I got a solution using https://github.com/chjj/marked. It allows you to pretty easily toggle features such as headings, images, etc.

Here's a list of the supported elements:

## Block
- [x] newline
- [x] code
- [x] fences
- [ ] hr
- [ ] heading
- [ ] nptable
- [ ] lheading
- [x] blockquote
- [x] list
- [ ] html
- [x] def
- [ ] table
- [x] paragraph
- [x] text

## Inline
- [x] escape
- [ ] autolink - we already use https://github.com/cowboy/javascript-linkify, which is pretty aggressive if you ask me, for this.
- [ ] url
- [x] tag
- [ ] link
- [ ] reflink
- [ ] nolink
- [x] strong
- [x] em
- [x] code
- [x] br
- [x] del
- [x] text

Which do we want by default (I've included my proposal) and should this be configurable so people running their own instance could allow all?

**Comment by cmaish** [comment]
This is done and deployed, right?

**Comment by hnrkndrssn** [comment]
I believe so...

**Comment by cmaish** [comment]
OK, closing - I think that we should be creating new issues for enabling or adding other formatting options.
