### ISSUE TITLE
Resend failed message improvements

### ISSUE THREAD

**Issue by hnrkndrssn** [JabbR/JabbR#1159]
Currently if you send `/foo` the resend icon will show and allow you to resend the message, this should not happen.

If you are not connected the resend function should not be available.

**Comment by jrmcdona** [comment]
If I grab this fix, it will include your other initial attempts to correct? I don't need to pull all of them in sequence?  Or basically, if I pull this one, it pulls all the latest dev PRs in with it so its a updated DEV branch per say.   Thanks

**Comment by hnrkndrssn** [comment]
The PR for this was built on top of the latest `dev` branch, so yes, if you pull this into your source, you should have an up-to-date branch with the latest fixes as of 812341cf856aa573deb42dd01d4e7ac27f900511

**Comment by cmaish** [comment]
Fix'd in dev
