### ISSUE TITLE
Upload Error!!!!

### ISSUE THREAD

**Issue by Moantonio** [JabbR/JabbR#1202]
Uploading descarga.jpg.
Failed to upload descarga.jpg.
Debug Step by Step, handler == null, what is my error? 
need to configure?
![image](https://cloud.githubusercontent.com/assets/8619642/4295857/b269734a-3dee-11e4-941d-c93b87b18ae5.png)

**Comment by cmaish** [comment]
Hi Moantonio!

Handler == null is something that is valid here (the next line is an exit when handler == null).  It sounds like yes, you need to configure your instance by giving it credentials for azure blob storage, which you can do through the admin settings page (visible at the top right of the chat screen when you're logged in as an admin).

Please feel free to reopen this issue if you have storage configured but it's not working for whatever reason.

**Comment by Moantonio** [comment]
ok, please give me an example that I set for file storage.
thank you Cmaish, 
![image](https://cloud.githubusercontent.com/assets/8619642/4296629/9f762236-3dfa-11e4-806f-31e432f91937.png)

**Comment by cmaish** [comment]
Which formats have you tried?

**Comment by Moantonio** [comment]
I do not know what format to put, an example please

**Comment by Moantonio** [comment]
I have a folder that says azure solution: 
![image](https://cloud.githubusercontent.com/assets/8619642/4304692/a99a3c7a-3e72-11e4-83fe-2d836db2b02e.png)

But in the project Jabbr not have a relationship with that "Azure" folder
where I get that format, or that part of the application have to modify, ????
