### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by Moantonio** [JabbR/JabbR#1203]
Uploading descarga.jpg.
Failed to upload descarga.jpg.
![image](https://cloud.githubusercontent.com/assets/8619642/4311355/0da9d26c-3eae-11e4-8303-a81ea9786b17.png)

Debug Step by Step, handler == null, what is my error? 
need to configure?
![image](https://cloud.githubusercontent.com/assets/8619642/4311276/6bf27208-3ead-11e4-881e-b4ad99115b98.png)

ok, please give me an example that I set for file storage.
thank you Cmaish, 
![image](https://cloud.githubusercontent.com/assets/8619642/4311283/7650fb5c-3ead-11e4-9c89-4d33f8024cfd.png)

I do not know what format to put, an example please

I have a folder that says azure solution: 
![image](https://cloud.githubusercontent.com/assets/8619642/4311289/8c7332a6-3ead-11e4-8a3a-4934eb29dd34.png)

But in the project Jabbr not have a relationship with that "Azure" folder
where I get that format, or that part of the application have to modify, ????

**Comment by cmaish** [comment]
http://msdn.microsoft.com/en-us/library/azure/ee758697.aspx
