### ISSUE TITLE
Suggestion: Togglable "Collapse Rich Content By Default"

### ISSUE THREAD

**Issue by damccull** [JabbR/JabbR#1218]
I think it'd be a nice addition to the web client to be able to choose to see all rich content collapsed by default, or even more granular control to collapse certain types by default.

For instance, sometimes people post gist links, and if you have rich content enabled, the content of that gist is embedded in the chat. You can manually collapse it, but it'd be nice to be able to let it START collapsed, because those things can get quite long sometimes.

**Comment by Buildstarted** [comment]
You can already disable rich content on a per-room basis. Via the `room settings`.

**Comment by damccull** [comment]
I saw that, but then it seems to he completely disabled. My idea is that it
just starts out collapsed and you can expand it manually.
