### ISSUE TITLE
Cannot delete account

### ISSUE THREAD

**Issue by andyleejordan** [JabbR/JabbR#1246]
Hello,

I have nothing against JabbR and think it's a great project; however, I haven't used it whatsoever. I'd like to delete my jabbr.net account, but cannot find a way to do so.

**Comment by andyleejordan** [comment]
/cc @cmaish

Would _really_ like to delete my account from the jabbr.net server.

**Comment by cmaish** [comment]
Hi @andschwa, I wish that I could help you, though I'm (well, was historically) involved in the JabbR product (running on-premise installs), while JabbR.net is a hosted instance managed by a couple of the others who worked on the codebase.

Over at jabbr.net, I'm just a user (though I do know that davidfowl was one of the admins).  You might be able to get in contact with someone responsible for running the server either in the meta room on jabbr.net, or by reaching out directly via eg twitter.

I'll leave this open as it's a valid issue with the product, and having an open issue should give more chance that the jabbr.net admins will see your message.  I hope that they do see this and can get your account change sorted out.

**Comment by andyleejordan** [comment]
Thanks for the timely response @cmaish (apparently I'm two years late thanking you though 😄 ).
