### ISSUE TITLE
slow ajax history can cause chat messages to show up out of order

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#129]
http://i.imgur.com/E6dFY.png

When loading a room for the first time and a message is received before the request for the room history can finalize the messages may be duplicated or appear out of order.

Possible steps to duplicate: leave a room, re-enter room and receive message before history is loaded (or use an addon like tamper form to pause the history loading for a bit)

**Comment by davidfowl** [comment]
Should be fixed now
