### ISSUE TITLE
OSX Chrome has wrapping issues

### ISSUE THREAD

**Issue by kathryn-thompson** [JabbR/JabbR#133]
In Chrome on OSX the dates on the right hand side are wrapped badly

http://imgur.com/9XWS7

Edit : Edited after complaints about my choice of image hosting

**Comment by davidfowl** [comment]
All yours @Kiliman

**Comment by kiliman** [comment]
@gordonthompson, I don't have a Mac, so can't test. Can you use Chrome Developer Tools and let me know what the dimensions are for the timestamp DIV.

See screenshot for example (on Chrome Win7)

http://www.systemex.net/files/JabbR/timestamp-size-issue.png

**Comment by kathryn-thompson** [comment]
85px x 16px

**Comment by kiliman** [comment]
Fixed in 3fff12c
