### ISSUE TITLE
Can't change username

### ISSUE THREAD

**Issue by phillip-haydon** [JabbR/JabbR#136]
Help specifies that:

nick - Type /nick [user] [password] to create a user or change your nickname.

But when trying to change the nickname, it says: 

Unable to find user 'Test123'.

The message indicates that the user doesn't exist (picking a username that does exist gives the message you can't change the password for a nickname you don't own)

**Comment by davidfowl** [comment]
You don't need to specify a password to change your nick name. Maybe the error/help should be better. The syntax is:

```
/nick name password - create a user name with password (if user does not exist). OR claim user name if not logged in
/nick name - changes the name of your current user
```

**Comment by phillip-haydon** [comment]
Yeah the text is misleading. 

Changing nickname works fine, but just need to update the help text.
