### ISSUE TITLE
Significant number of tabs may force tabs under other page elements.

### ISSUE THREAD

**Issue by steingrim** [JabbR/JabbR#138]
Significant number of tabs may force tabs under other page elements.

Add enough tabs and the last tab on the row may be forced below the 'Fork me on github' graphic.

More than one row of tabs and the tabs start partially appearing 'behind' the chat window and the users/room list.

Extreme example here from IE 9:

http://www.alliedstates.org/week4/tabsoddness.png

**Comment by davidfowl** [comment]
Anything on this?

**Comment by JesseBuesking** [comment]
I can see this happening too even on Chrome when I shrink my browser's width.  

For now why not throw an `overflow: hidden` on the ul to avoid the wrapping issue.   Moving forward, maybe the tabs should switch up to a select box when the device's width is smaller than x pixels.  Scott Hanselman mentions this [here](http://www.hanselman.com/blog/LearningAboutProgressiveEnhancementSupportingMobileBrowsersWithCSS3MediaQueries.aspx), and you can see his navigation at the top change to a select box when you shrink the width of your browser.  Those are my ideas :D

Also, I could tackle this if we can figure out some way to manage this.

**Comment by adamralph** [comment]
Bump! I'll take a look and see if I can help on this one.

**Comment by damianh** [comment]
Considered tabs down the left side?

**Comment by samandmoore** [comment]
yes. we have. it doesn't scale well either.

**Comment by cmaish** [comment]
Tabs now fall into a bootstrap dropdown when they overflow.  This should be ok-ish on mobile devices, though we'll tackle some of the issues with small-format devices as a responsive design block.
