### ISSUE TITLE
Lobby should look different

### ISSUE THREAD

**Issue by paulbatum** [JabbR/JabbR#143]
This will make access keys more logical. At the moment its confusing that alt+1 takes me to the second tab. Different lobby styling will resolve the issue.

**Comment by haacked** [comment]
Ok, I'll take this one.

One more thing, I'd like a way to cycle through tabs. ALT + ArrowKey is already reserved for cycling through browser history. Alternatives?
- CTRL + ArrowKey? 
- ALT + Plus/Minus?
- Override arrow key anyways
- Other?...

**Comment by paulbatum** [comment]
How about alt+tilde

**Comment by haacked** [comment]
How's this look?

**Selected**
![Selected](http://i.imgur.com/3EjsP.png)

and

**Not Selected**
![Not Selected](http://i.imgur.com/sOund.png)

**Comment by paulbatum** [comment]
Looks good!

**Comment by haacked** [comment]
How about `shift+tab`?

**Comment by haacked** [comment]
Ok, I think I'll split this into two bugs. One for the lobby. One for the cycling.
