### ISSUE TITLE
Using nick with a password while already logged in doesn't work

### ISSUE THREAD

**Issue by davidebbo** [JabbR/JabbR#152]
On one machine, I'm logged in with a password. On another one, I'm logged in as some random name.

Then I run /nick MyName MyPassword and it fails with `You can't set/change the password for a nickname you down own.`. I had to first log out.

Ideally it should just work. Or at least the error message should suggest doing a /logout

**Comment by kiliman** [comment]
Yes, I believe if you know the password, you should be able to claim the nick on any client regardless of your login status.

**Comment by davidfowl** [comment]
We need to properly clean up the previous user's state. It's alot easier to let the user do that, so I think we should just fix the error message to tell them to logout so it's clearer.
