### ISSUE TITLE
Allow me to sign in using twitter (or google, etc) credentials

### ISSUE THREAD

**Issue by paulbatum** [JabbR/JabbR#155]
Passwords are lame, don't make me have another one. Let me use twitter or google, etc to sign in.

**Comment by davidfowl** [comment]
I agree this is an awesome feature to have. Funny thing. You only have to enter you password once per client and you're done. So it's not as big a hassle as you make it sound. Regardless this is low priority unless awesome contributor decides to do it :)

**Comment by paulbatum** [comment]
Done.. until you forget it :) Long term is not as easy as you say.

Agree its low priority.

**Comment by davidfowl** [comment]
Done!

**Comment by paulbatum** [comment]
Awesome :)
