### ISSUE TITLE
ContentProviders should be required to have a unique name or id

### ISSUE THREAD

**Issue by sethwebster** [JabbR/JabbR#173]
This way, they can be referenced in the interface such that they can be managed -- hidden, shown globally etc.

For example, you can show/hide single items now but this would enable (among other things) disabling all posts by a specific provider -- "Hide all College Humor Posts"

**Comment by davidfowl** [comment]
why can't it just be the type name?

**Comment by sethwebster** [comment]
Could be, but I think a Display name would be nice.  Maybe an _and_...

If we create UI for hiding/showing, it would be nice to have something other than the type name.  Type name will work great for id'ing them in the markup though.

**Comment by davidfowl** [comment]
Display name != unique id. That's separate.

**Comment by sethwebster** [comment]
Yeah, I agree. That's what I meant by it's an _and_... Two things.

**Comment by davidfowl** [comment]
The bug says "or" :)

**Comment by sethwebster** [comment]
LOL.
