### ISSUE TITLE
Add support for banning users

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#185]
When we start getting spammers we'll need the /ban command.

**Comment by samandmoore** [comment]
`/ban` command, bans user via some sort of bit field in the ChatUser table?

**Comment by samandmoore** [comment]
via @davidfowl "We should figure out if we ban per room also. Maybe there's different levels of granularity..."

**Comment by samandmoore** [comment]
We only need granularity for banning, room v. user, if we are giving this ability to owners as well as admins. The way i see it, if an admin wants to ban someone then it would be sitewide, but owners should not have that level of power.

**Comment by davidfowl** [comment]
http://www.codinghorror.com/blog/2011/06/suspension-ban-or-hellban.html

**Comment by davidfowl** [comment]
This is done.
