### ISSUE TITLE
Show rooms sorted by activity and/or number of users

### ISSUE THREAD

**Issue by davidebbo** [JabbR/JabbR#189]
With a growing number of 'dead' rooms, it's hard to know where the action is. I would prefer if the rooms were sorted by amount of recent activity or number of users (or some similar metric that reflects activity).

**Comment by davidfowl** [comment]
@Kiliman, what do you think about this one? Should we hide empty rooms or just sort them to the bottom?

**Comment by kiliman** [comment]
If we're going to sort by activity and user count, then we might as well show empty rooms as well. This will also make #195 irrelevant.

**Comment by davidebbo** [comment]
Awesome!
