### ISSUE TITLE
a message if the chat goes down

### ISSUE THREAD

**Issue by cplussharp** [JabbR/JabbR#19]
a message to the user if the chat goes down would be good.
Now it only stops to work, no new entries apear and if i try to post i get "pleas choose a nick"

Or even beeter would be an reload of the page and autologon

**Comment by steingrim** [comment]
I’ve seen a couple of chats which spam the chat with ‘no connection’ messages. This gets problematic. I’d prefer something more like ‘Trying to reconnect to the chat server’ or an icon which shows if connected or not.

**Comment by davidfowl** [comment]
What's this 'no connection' message you're talking about?
