### ISSUE TITLE
Need a way to close a room

### ISSUE THREAD

**Issue by haacked** [JabbR/JabbR#190]
If you create a locked room, you can never unlock it (privacy concerns). So that room name is effectively locked forever. Would be nice to be able to close a room so the name frees up.

**Comment by PureKrome** [comment]
Out of interest .. should this then delete the entire history of the room and the room itself from the DB?

If not .. (say .. for archiving purposes) ... 
- How would anyone get access to it? Only via the DB?
- Do we care about archiving?
