### ISSUE TITLE
Make JabbR localizable

### ISSUE THREAD

**Issue by tbolon** [JabbR/JabbR#196]
I think JabbR should adopt a way to make the UI localizable.

I've already checked how jQueryUI components, such as the [DatePicker](https://github.com/jquery/jquery-ui/blob/master/ui/i18n/jquery.ui.datepicker-fr.js) uses external resources.

For formatted strings, we could use a function with parameters ? eg. : `enteredRoom: function(nick, room) { return nick + ' just entered room ' + room; }`, but there are certainly better ways to do this.

I could help to translate and organize resources, but I prefer that one of the main contributors start with overall architecture.

**Comment by davidfowl** [comment]
If you feel passionate about it, feel free to step in and make those changes :)

**Comment by tbolon** [comment]
I'll try to handle this on my fork, but I'm really new to github, and try to submit a patch.

If someone is interested in helping on this, I'll be happy to take other advises and suggestions.

**Comment by davidfowl** [comment]
Sure, are you planning to localize the entire chat or do you just want to make it localizable.

**Comment by tbolon** [comment]
I've got some end-users from a community which will be happy to test and use JabbR, but they are definitively not fluent in english.

So my goal is to translate the whole UI into french.

Instead of simply replacing all text strings in my fork, I think it will be usefull if I allow other contributors to translate JabbR for other languages.

My biggest question concerns the choice on how to store and retrieve resources. the jQueryUI datepicker seems to be the obvious one, but I don't know if they are "better" alternatives.

So, for your question, I'll anwser "both".

**Comment by daanl** [comment]
This plugin also helps: https://github.com/jquery/globalize

Maybe ask server for resource file?

**Comment by tbolon** [comment]
That was exactly that kind of advices I was looking for :)

I love the `File.lang.js` convention for including resources, where datas are stored as simple javascript object. It could allow dynamic loading and/or static linking based on needs. If you want to force your ui in a certain language, you can. If you want to load it based on browser languages, it's also possible.

**Comment by InfinitiesLoop** [comment]
FYI jQuery/Globalize is what was once the globalization library in ASP.NET AJAX. You might think that's a bad thing :) But it was one of the gems of it. It's based on the rich .NET globalization information, which is why there's like 300+ cultures supported. Also, and more importantly, jQueryUI is planning on using it for its own globalization in the future. So it's got a backing and a future, probably.

**Comment by davidfowl** [comment]
Any progress on this?

**Comment by tbolon** [comment]
Nothing new here, I was busy with other projects on my free time. It's still on my todo list.

FYI, I've seen that JQuery Globalize has a [nuget package](http://nuget.org/packages/jquery-globalize).

**Comment by schulz3000** [comment]
I want to bring up this topic again.
In my view there are two parts for localization, server and client side.
I don't know much about localization at client side so it will be not my subject for now.
But I'm interested in the server side localization. I think it's relative simple doing it with Resources. The main question for me here is, are there any naming conventions for the resource variables?

**Comment by davidfowl** [comment]
@schulz3000 Let's get some of your work integrated back into the core.

**Comment by cmaish** [comment]
An implementation of this is now in dev and should find its way to prod soon
