### ISSUE TITLE
Feature: Timestamp on messages

### ISSUE THREAD

**Issue by schotime** [JabbR/JabbR#2]
It would be nice if there was a timestamp on messages, so that if you duck off for a few minutes you know when messages were sent.

As a side note, /j and /n should be able to be used as aliases for /join and /nick.

**Comment by davidfowl** [comment]
2 bugs in one :P. How do you think the date should be rendered?

**Comment by schotime** [comment]
Could probably just have  

[HH:mm] Nickname: Message

or a longer version of the date.
