### ISSUE TITLE
remove empty rooms

### ISSUE THREAD

**Issue by cplussharp** [JabbR/JabbR#20]
if somebody starts a new room with '/join roomxyz' the room stays in the '/rooms' list even if nobody is there.
It would be better if empty rooms are removed from the list

**Comment by steingrim** [comment]
This is potentially problematic. For instance: You’re going to chat with someone. They’re late. You leave a message in the chat. Have meeting. Will try to catch you in an hour. You leave the room, the message is lost.

Some people really like some persistence in a chatroom. My suggestion would be to have the default persistence to be open and let people set a lower persistence value. This would let rooms have a sort of ‘garbage collection’ set by the site admin.

**Comment by davidfowl** [comment]
This will be an admin/owner feature.
