### ISSUE TITLE
YouTube Content Provider should inform if video can't be loaded due to Login Required (403)

### ISSUE THREAD

**Issue by sethwebster** [JabbR/JabbR#201]
Earlier, an 18+ video was posted and it failed because JabbR was not logged in and thus couldn't prove its age.  The provider should recognize the 403 and Inform the chat room that they need to log in to see the video.

**Comment by davidfowl** [comment]
How would they log in?

**Comment by sethwebster** [comment]
Content Provider would provide experience (if they are not logged in; if they are, video renders) like:

To view this video, you must log in by clicking [here].

Then we'll pop them out or something.

**Comment by cmaish** [comment]
This has been deprecated from the youtube side of things.  http://www.youtube.com/watch?v=pDOmwjgKBcI is an age-restricted video, but embedding on it works.  Even pay-to-view videos such as http://www.youtube.com/movie?v=LFL4UnYvaGE work as expected (whether you're logged in or not).

If anyone runs into this problem in the future, please feel free to reopen this issue.
