### ISSUE TITLE
The '...' should not be shown for the current user

### ISSUE THREAD

**Issue by davidebbo** [JabbR/JabbR#209]
I often start typing then notice the '...' and figure someone else is typing. Then realize it's me :)

So I think it's be better if I didn't see my own '...'

**Comment by davidfowl** [comment]
Why not? Does it confuse you?

**Comment by davidebbo** [comment]
Yes, because when having a 1 on 1 conversation, I'm conditioned to stop typing when I see that the other guy is. We all sort of do that on IM. Here it takes extra efforts to mentally filter out your own noise.
