### ISSUE TITLE
jabbr.net crashes Safari on iPhone

### ISSUE THREAD

**Issue by davidebbo** [JabbR/JabbR#214]
Safari instantly crashes. Fascinatingly, it only happen on 3G (AT&T), and not on WiFi. Bizarre!

**Comment by davidebbo** [comment]
It looks like this may be a general issue with WebSocket on iPhone when going through Onavo (a compression proxy). While not a JabbR issue, JabbR could conceivably support a ?websockets=0 mode where it would not use websockets even when available on the browser.

**Comment by davidfowl** [comment]
This should be fixed now
