### ISSUE TITLE
Bug in date separator

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#219]
When we add notifications, we do it on the client only and there's a discrepancy with times:

http://i.imgur.com/u1LWs.png

So it applies the date separator between notification messages and messages that come from the server.

**Comment by davidfowl** [comment]
Looks like it's a bug with `toLocaleTimeString` in chrome: http://code.google.com/p/chromium/issues/detail?id=3607.

**Comment by davidfowl** [comment]
Might not be a real issue at all, I closed and re-opened my browser window and it worked just fine.

**Comment by kiliman** [comment]
I can't repro this. Since you said it is working for you now, can we close this out?

**Comment by davidfowl** [comment]
Nuke it

Sent from my Windows Phone
