### ISSUE TITLE
still in room

### ISSUE THREAD

**Issue by cplussharp** [JabbR/JabbR#22]
if i fast create many rooms with '/join room1' '/join room2' and so on. im still registered in some rooms.
Sometimes if i try to enter such a room i get 'you are already in this room' and sometime i can enter it.
If i enter and leave such a room and show the list again, there is still someone in this room [room has a (1)]

**Comment by mteper** [comment]
A thought: how about an extension to the /leave command that takes the name of the room? This may not fix the stale room membership issue that's creeping up under weird circumstances and may be hard to plug, but would at least let the user fix it themselves.
