### ISSUE TITLE
Change /who to /where and make it work

### ISSUE THREAD

**Issue by haacked** [JabbR/JabbR#220]
Right now, `/who` shows me a list of rooms for a user even if the user is not logged in. Broken!

In fact, the command should be `/where _username_` instead of `/who`. Then make `/who` show user information such as:
- status (active, inactive, last seen)
- rooms owned.
- rooms created.

**Comment by sethwebster** [comment]
#220 Update staged here - http://seth-jabbr.apphb.com.

Let me know what you think, @Haacked.
