### ISSUE TITLE
Tab flashing. Alarm type UI elements should have overrides in user preferences.

### ISSUE THREAD

**Issue by steingrim** [JabbR/JabbR#243]
The tab flashing is a bit jarring and difficult to ignore, though I can see why some people like it. We’re all going to have different likes and dislikes as well as different views as to what colors to use, what sounds, should things flash or not, and so on. 

This is probably at least the third notification scheme put in place for tab updates, with each one some seem to like the change, others not so much. Instead of tossing out the work previously done, why not just let the users themselves decide and set their own preferences instead of micro-managing minutia such as how thick should some line be?

**Comment by davidfowl** [comment]
We didn't make this a preference but it blinks a fixed number of times and remains highlighted as a compromis.
