### ISSUE TITLE
Is mobile busted?

### ISSUE THREAD

**Issue by steingrim** [JabbR/JabbR#244]
Mobile.hml doesn’t appear to be functioning. Not surprising given all the great and frequent changes, but I thought worth mentioning.

**Comment by kiliman** [comment]
That was the original mobile page before we added multiple chat rooms. I'm working on the new mobile UI.

**Comment by steingrim** [comment]
Danka!

**Comment by davidfowl** [comment]
@kiliman any updates on mobile?

**Comment by davidfowl** [comment]
@kiliman come back and fix it :).
