### ISSUE TITLE
Twitter Provider links broken?

### ISSUE THREAD

**Issue by steingrim** [JabbR/JabbR#245]
In http://twitter.com/#!/sgMarshall/status/147499152367038464 the link is not clickable. Additionally, the link the provider attempts to display is changed from bit.ly to t.co (perhaps the link is being reincoded and altered)?

**Comment by sethwebster** [comment]
@traemarshall -- the t.co transformation is done by twitter by the time we get the JSON response.  I'll make sure links get linked.

**Comment by steingrim** [comment]
Thanks for the quick fix. You rock!

**Comment by sethwebster** [comment]
:)
