### ISSUE TITLE
/who and /where seem slightly out of sync.

### ISSUE THREAD

**Issue by steingrim** [JabbR/JabbR#251]
Some people are used to using /who and others /where. Currently both return simular types of information when the parameter is a user. Perhaps most of that common code should be a common method? It appears to me that it is only with the non-parameterized commands that there's a real difference in the data that should be returned.

/who sgmarshall
sgMarshall is in the following rooms
11:28:01 PM
meta, signalr, WP7, nuget, EntityFramework, aspnetmvc, TFS, VisualStudio, UnitTesting, jquery, general-chat, csharptube, buildstarted
sgMarshall owns the following rooms
11:28:01 PM
VisualStudio, UnitTesting 

/where sgmarshall
sgMarshall is in the following rooms
11:28:23 PM
meta, signalr, WP7, nuget, EntityFramework, aspnetmvc, TFS, VisualStudio, UnitTesting, jquery, general-chat, csharptube, buildstarted

**Comment by sethwebster** [comment]
@traemarshall  -- I updated /who & /where as part of another issue you submitted. 

What do you think now?

**Comment by steingrim** [comment]
Looks great. Thanks!
