### ISSUE TITLE
Blinking tabs when someone mentions you

### ISSUE THREAD

**Issue by runesoerensen** [JabbR/JabbR#254]
Currently a room tab blinks when someone has written a message. It'd be nice if the tab only blinks when someone specifically mentions the signed in user. The (count) already indicates that someone else has written something in the room, although they didn't mention the user.

**Comment by davidfowl** [comment]
I made it blink less. Only 6 times now :). How's that?

**Comment by runesoerensen** [comment]
Better - thanks! :-)

**Comment by davidfowl** [comment]
Nice :)
