### ISSUE TITLE
Automatically list chat rooms when opening chat site

### ISSUE THREAD

**Issue by KirillOsenkov** [JabbR/JabbR#27]
Ideally use links so that I don't have to type /join etc. Just open the website, click a link and you're good!

**Comment by davidfowl** [comment]
Don

**Comment by sun6174** [comment]
Hi.. how can i list the chat rooms to make them display from database

**Comment by davidfowl** [comment]
What?

**Comment by KirillOsenkov** [comment]
No clue (Sun6127???)

Sent from my Windows Phone

**Comment by sun6174** [comment]
@davidfowl  I mean, on the right the side of the jabbr.net chat application, the list of the rooms are displaying in clickable fashion in an arbitrary way. How can i suppose to load those rooms from the database? I don't know how exactly the rooms are loading in https://github.com/davidfowl/JabbR . Please don't mind..I am just new to these things. :)
