### ISSUE TITLE
Sound notifications - Not working / Intermittent.

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#270]
The spec specifies - 
"Adding a notification sound when you get a pm & when you get a mention in an inactive room or when the window does not have focus."

This does not appear to work as expected. Tested using Chrome and IE.

Steps taken:
Two parties attempted to ping each other whilst the other had focus on another window. 
Two parties attempted to ping each other whilst the other was in another room.

**Comment by davidfowl** [comment]
Sound/Popup notifications only ever happen when you don't have focus.

**Comment by DavidChristiansen** [comment]
Hi mate, Yes That's what we thought but nomatter what we tried we couldn't get it to fire. I've forked the repo to try and recreate locally and will report back here.

**Comment by davidfowl** [comment]
Any repro?

**Comment by DavidChristiansen** [comment]
Unable to reproduce
