### ISSUE TITLE
Pressing the up arrow loses what you had typed in the message box

### ISSUE THREAD

**Issue by DamianEdwards** [JabbR/JabbR#279]
This is _really_ annoying if you accidently hit the up arrow. I do this most in a long reply when it wraps to multiple lines in the message text box and then try to navigate the cursor "up" to the previous line to make a change. It's all 1 line of course but my muscle memory kicks in and then I lose everything I typed.

I suggest we make the previous messages feature snapshot what was in the message box when the arrow is first pressed, so that it can be cycled back to, just like it was a previous message.

**Comment by davidfowl** [comment]
This is fixed

**Comment by PureKrome** [comment]
Awesome! This has been bugging me for ages, also :P
