### ISSUE TITLE
Keep focus when changing tabs

### ISSUE THREAD

**Issue by dannylloyd** [JabbR/JabbR#287]
When switching tabs, the focus is lost from the textbox. I don't know if it's just me, but I like to switch tabs and begin typing, I have switch tab then click on the textbox to type a message.

**Comment by DamianEdwards** [comment]
Agreed, particularly annoying when using keyboard shortcuts to move to
new tabs.

Sent from my Windows Phone
From: dannylloyd
Sent: 1/9/2012 10:46 AM
To: DamianEdwards
Subject: [JabbR] Keep focus when changing tabs (#287)
When switching tabs, the focus is lost from the textbox. I don't know
if it's just me, but I like to switch tabs and begin typing, I have
switch tab then click on the textbox to type a message.

---

Reply to this email directly or view it on GitHub:
https://github.com/davidfowl/JabbR/issues/287

**Comment by dannylloyd** [comment]
Off-topic, but where can I find the keyboard shortcuts?

**Comment by DamianEdwards** [comment]
I just meant the accesskey attribute which we populate for a bunch of
links, like the tab headers.

Sent from my Windows Phone

**Comment by dannylloyd** [comment]
Cool, those are nice. It makes this focus feature all the more important.

**Comment by dannylloyd** [comment]
There is an accesskey for the message textbox, "m".

**Comment by davidfowl** [comment]
This is still broken for ipads. They aren't detected properly and it makes the keyboard show up whenever rooms are switched.
