### ISSUE TITLE
Add emoticon when entered in chat

### ISSUE THREAD

**Issue by dannylloyd** [JabbR/JabbR#290]
Turn this :<br/>
:)

into this : <br/>
![Emoticon](http://www.tutorialsscripts.com/free-icons/skype/emoticons/emot-icon/emoticon-big-smile-32px-image-picture.png)

**Comment by rpgmaker** [comment]
This would definitely be a nice to have

**Comment by dannylloyd** [comment]
Duplicate of another issue https://github.com/davidfowl/JabbR/issues/106
