### ISSUE TITLE
Auto-kick Idling Users

### ISSUE THREAD

**Issue by andrewtobin** [JabbR/JabbR#305]
I think any users who have been inactive for a period longer than an hour should be auto-logged off.

It would free up connection and resources, and there is already a mechanism to retrace the history of a room, so they don't "miss" anything.

There are a lot of people who seem to remain logged in overnight through wanting to camp/lurk or just forgetfulness on logging out.

I think if you had those connections free it would significantly free resources on the apphb instance.

**Comment by davidfowl** [comment]
Undeeded
