### ISSUE TITLE
Room topic / status

### ISSUE THREAD

**Issue by DavidBurela** [JabbR/JabbR#310]
**Overview**
A way for the owner of the room to set the room's "Status" or "Message of the day".
In each room, at the top of the chat window will be a small space where the MOTD is displayed

**Command examples**
/topic "Progress is going well, we now have messaging support"
/topic "Discuss Git issues in here"
/topic "Ask your NuGet questions here"

**Benefit**
Currently for rooms that are supporting projects, it can be difficult to just jump into a room and see the current status of a project without scrolling up and re-reading 4 hours worth of logs.
The owner is able to just set a message saying what the progress is _"Basic framework locked down, contributers should grab tasks 1-10 from Trello board"_

**Comment by davidfowl** [comment]
I like it and will implement it :)

**Comment by dpen2000** [comment]
I'll handle this.
