### ISSUE TITLE
Getting "Collection was modified; enumeration operation may not execute." when loading jabbr sometimes

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#311]
This shows up in the lobby on join sometimes.

**Comment by sethwebster** [comment]
Anybody have steps for repro?

**Comment by davidfowl** [comment]
Only live. Locally try creating a whole bunch of users in different rooms.

**Comment by davidfowl** [comment]
Also try loggin on with n clients same user.

**Comment by DavidChristiansen** [comment]
This is accompanied by many of these in the console.

Error raising received TypeError: Cannot read property 'scrollTop' of undefined
jquery.signalR.js:18

**Comment by davidfowl** [comment]
I'll take a look at this myself. It's annoying me.

**Comment by sethwebster** [comment]
Sorry man -- new job is sucking up my time :)

**Comment by davidfowl** [comment]
Corporate  drone :)

**Comment by sethwebster** [comment]
Totally.

**Comment by davidfowl** [comment]
I'm hoping I did something that fixed this.
