### ISSUE TITLE
User list sorted by activity status and name

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#312]
The user list on the right could be improved if it showed the currently active users at the top of the list, followed by those that are recently afk followed by those that haven't been seen for a long time.

**Comment by DavidChristiansen** [comment]
Please assign this to me.

**Comment by PureKrome** [comment]
for the UI, maybe put a line between the user 'groups'
1. active
2. afk
3. idle

```
eg. 
[O] DFowler [X]
[O] Mmmmmm [X]
[O] Ssssss [X]
[O] Zzzzzzzzzzzz [X]
----------------
[O] Bbbb [X] AFK
[O] Fffff [X] AFK
-------
[O] Aaaa [X] Idle
[O] Abbbbb [X] Idle
...
```

**Comment by davidfowl** [comment]
Owners should be at the top always.

**Comment by samandmoore** [comment]
This feature was implemented there is just no PR associated with it.

**Comment by DavidChristiansen** [comment]
My bad :(

**Comment by samandmoore** [comment]
No worries, just tidying up :)
