### ISSUE TITLE
Uncaught TypeError: Object 0 has no method 'toLowerCase'

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#316]
jquery.autotabcomplete.js:112

**Comment by DavidChristiansen** [comment]
Occurs when a user attempts to autocomplete a chatter's name by typing in a partial name and hitting tab.

**Comment by dpen2000** [comment]
I have a reproduction for this. If you're in a room with a user called "0" (a perfectly valid username at the moment), typing "@" and then tab produces another javascript error. This particular error occurs if you type "@" follows by any number of characters and press tab. When we pull user names out of data-user attributes, the 0 gets pulled out as an integer, not as a string and the presence of 0 or any other integer in the list of users causes error.
