### ISSUE TITLE
Collection was modified; enumeration operation may not execute. 

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#317]

**Comment by davidfowl** [comment]
Duplicate

**Comment by DavidChristiansen** [comment]
upon screen refresh - accompanied by many 

Error raising received TypeError: Cannot read property 'scrollTop' of undefined
jquery.signalR.js:18

**Comment by davidfowl** [comment]
of https://github.com/davidfowl/JabbR/issues/311
