### ISSUE TITLE
Room stops updating

### ISSUE THREAD

**Issue by kathryn-thompson** [JabbR/JabbR#319]
After a while the room stops refreshing and you don't get any messages until the browser tab is refreshed. The room we use is ukwarez. It seems to be non-browser specific (happens in Chrome on OSX on my machine, other users on windows have experienced the same problem)

**Comment by davidfowl** [comment]
There's a bug in signalr with server sent events not reconnecting. I'll switch to long polling for now.

**Comment by davidfowl** [comment]
Fixed in 429c554e46bd971b6c31a51cdc6c75e1a86151ee
