### ISSUE TITLE
JS/CSS resource versioning / caching

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#322]
To ensure clients are pulling down the most recent copy of JS and css files it is suggested that a build number is appended to the end of the resource url (i.e. "/Chat.js?version=1.0.0.0"). This way the client pulls down the latest version and only performs a refresh when the version number is changed.

**Comment by DavidChristiansen** [comment]
On apphb, we can use ?<%=ConfigurationManager.AppSettings["appharbor.commit_id"]%>

**Comment by redsquare** [comment]
You should not include a querystring for static resources since some proxies ignore them, should encode the version within the filename.

**Comment by DavidChristiansen** [comment]
Great advice Red, I didn't know that.

**Comment by davidfowl** [comment]
This is most likely fixed with recent changes to suport bundling.
