### ISSUE TITLE
Responsive web layout

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#326]
Rework the JabbR UI.

..."Responsive Web design is the approach that suggests that design and development should respond to the user’s behavior and environment based on screen size, platform and orientation. The practice consists of a mix of flexible grids and layouts, images and an intelligent use of CSS media queries. As the user switches from their laptop to iPad, the website should automatically switch to accommodate for resolution, image size and scripting abilities. In other words, the website should have the technology to automatically respond to the user’s preferences. This would eliminate the need for a different design and development phase for each new gadget on the market."

DC is currently working on this.

**Comment by samandmoore** [comment]
anything happening here?

**Comment by cmaish** [comment]
I'm going to call this done, particularly with #1045 in dev.  The same layout should mostly work on a wide variety of devices.  Specific responsive layout issues can be opened as new issues
