### ISSUE TITLE
Can't scroll to see previous chat history on high resolution monitors

### ISSUE THREAD

**Issue by TrentScholl** [JabbR/JabbR#336]
At 2560x1440, not enough previous chat messages are loaded to cause the scroll bar to show (unless images/youtube clips are in the history). This means you can't scroll up and trigger it to load previous history.

Workaround: Shrink the window down, scroll up and then maximize the window again.

Suggested Fixes: On room enter, display more messages regardless of resolution or on room enter, display number of messages based on resolution.

**Comment by davidfowl** [comment]
Yes this was changed to make the loading faster but we can see what number of messages works best.

**Comment by davidfowl** [comment]
Was fixed
