### ISSUE TITLE
Sprite-up emotion icons 

### ISSUE THREAD

**Issue by redsquare** [JabbR/JabbR#339]
Rather than including lots of individual images lets sprite up the emotions and render spans with the background image x,y set via a css class

**Comment by JesseBuesking** [comment]
I was thinking the same thing.  I wouldn't mind doing this one.

**Comment by redsquare** [comment]
Did you get a chance to look into this jesse?

**Comment by JesseBuesking** [comment]
Not yet.  You can take a look if you'd like.
