### ISSUE TITLE
Private Messages dont turn urls into clickable links

### ISSUE THREAD

**Issue by ignaciofuentes** [JabbR/JabbR#354]
Im not sure if the policies for content providers should apply exactly for private messages but i think that urls should at least be clickable and not just some text you need to copy and paste for it to actually have any value.

**Comment by davidfowl** [comment]
They are

Sent from my Windows Phone
From: nacho10f
Sent: 2/1/2012 1:43 PM
To: David Fowler
Subject: [JabbR] Private Messages dont turn urls into clickable links
(#354)
Im not sure if the policies for content providers should apply exactly
for private messages but i think that urls should at least be
clickable and not just some text you need to copy and paste for it to
actually have any value.

---

Reply to this email directly or view it on GitHub:
https://github.com/davidfowl/JabbR/issues/354

**Comment by ignaciofuentes** [comment]
correct. my outdated local copy didnt do it.
