### ISSUE TITLE
Allow room owners to disable emoticons

### ISSUE THREAD

**Issue by mythz** [JabbR/JabbR#366]
IMO the current use of emoticons often seems gets in the way of pasting C# source code in chat.
It would be nice if room owners could disable emoticons on a room-by-room basis.

**Comment by davidfowl** [comment]
I don't the room granularity, I think this should be per client.

**Comment by mythz** [comment]
Is this the sending or receiving client? IMO it makes more sense for the sending client

**Comment by davidfowl** [comment]
It's like windows live messenger You can turn off what you end up seeing on your client, but you can't turn on emoticons for me.

**Comment by mythz** [comment]
but it doesn't help the guy who's pasting his beautiful source code that unknowingly ends up full of smiley faces, rainbows and unicorns!

**Comment by davidfowl** [comment]
That'ts just a bug :)
