### ISSUE TITLE
Suggestion for auto completion

### ISSUE THREAD

**Issue by txdv** [JabbR/JabbR#368]
I will be representing the cursor position as the | char:
When one does autocomplete a nick, it gets autocompleted from "@t|" to "@txdv|", I would suggest that the proper completion result should be "@txdv |"
In other words with a space between the new cursor position and the nick!
This behaviour is the usual expected behavior in chat systems like this (irssi, mirc, etc...).

**Comment by kiliman** [comment]
Making this change would be easy, however a lot of users are used to the current behavior and already typing the space after Tab. My concern is that people will complain about the "extra" space begin added.

I just checked StackOverflow's chat, and it works just like ours. It does not include the trailing space. Although Twitter does add the extra space. So it doesn't look like it's very consistent.

I wonder if this should be something configurable by each user (although I'm not a big fan of having options for everything).

**Comment by txdv** [comment]
irssi has this behaviour and irssi is the godfather of all chatting.
If there is one right way, this is the one!

**Comment by davidfowl** [comment]
Yea lets not have options, we can ask ppl in chat what they think and pick one and stick with it.

**Comment by samandmoore** [comment]
I'd prefer to have it auto-include the space.

**Comment by samandmoore** [comment]
we're now automatically adding the space after @, #, and / autocompletes.
