### ISSUE TITLE
Disable notification on rooms

### ISSUE THREAD

**Issue by thecodejunkie** [JabbR/JabbR#386]
It would be handy to disable notification on any room you'd like. Some rooms aren't that important to me and I'd like to avoid getting a seizure of I don't check the updates of the room ;)

**Comment by ctolkien** [comment]
Further on this, I think it would be good to stop the blinking after X number of blinks

**Comment by davidfowl** [comment]
@ctolkien's suggestion is a good balance.

**Comment by thecodejunkie** [comment]
I disagree this doesn't really touch at the reported issue. If you have several tabs open and some you don't really care about notifications then you are still going to get epilepsy =) A busy room will still blink for as long as you keep the tab open

**Comment by davidfowl** [comment]
Yep but blinking less eases the pain. I went for a compromise that is
think is reasonable.

Sent from my Windows Phone

**Comment by drub0y** [comment]
@davidfowl Totally agree with this as compromise, but do you think you could have it end the blinking on the highlighted color? That way when we're not staring at the screen and come back we can distinguis what rooms actually had activity since last we looked?

**Comment by davidfowl** [comment]
Sounds good.

Sent from my Windows Phone
