### ISSUE TITLE
Empty previous message list

### ISSUE THREAD

**Issue by Amir978** [JabbR/JabbR#387]
I'm trying to use Jabbr in my MVC project. I've added all files to same folders in my MVC project and customized chat rooms based on my project customers groups. Every thing works fine except the previous message list. The difference is I'm using Ado.Net entity Data Model (.edmx) and it's not 'CodeFirst' nor 'ModelFirst' approach (I'm not using JabbrContext) , so I can't take advantage of DbSet properties in DbContext and  the " DbSet <ChatMessage> messages" returns nothing. In the other words, how can I add `public DbSet<ChatMessage> Messages { get; set; }` to my entity data model?

**Comment by davidfowl** [comment]
You can query your own set of messages. I'm not sure what you're doing in your version of jabbr so I'd need more details in order to help you.

**Comment by Amir978** [comment]
How can I populate the 'Room' values of 'ChatMessage' class(model)? 'Room' is not mapped to any field in database (in ChatMessages table) , so I can't populate it in GetPreviousMessage (in PersistedRepository)

**Comment by davidfowl** [comment]
You have the code don't you? Can't you change change it?
