### ISSUE TITLE
Auto Link Creation Doesn't Handle URLs With Parentheses

### ISSUE THREAD

**Issue by DanRigby** [JabbR/JabbR#388]
The logic that turns URLs into links when used in chat doesn't handle URLs that contain parentheses. It terminates the link at the first parentheses encountered.

Ex: http://msdn.microsoft.com/en-us/library/dd547188(v=vs.110).aspx

**Comment by admsteck** [comment]
I'm  working on this

**Comment by davidfowl** [comment]
Fixed
