### ISSUE TITLE
JabbR prevents sharing of certain connection strings

### ISSUE THREAD

**Issue by dotnetchris** [JabbR/JabbR#389]
I tried to paste the code sample:

&lt;add name="RavenDB" connectionString="Url=http://localhost:8080;ResourceManagerId=GUID" />

And was presented with an error: Invalid URI: Invalid port specified. 

I don't feel this should be an error, if you can't parse the url you should just let it degrade to regular text.

**Comment by davidfowl** [comment]
Jabbr doesn't support RavenDB. If you'd like to add support for it we gladly accept pull requests.

**Comment by davidfowl** [comment]
Wait are you saying we parse this? What does the stack trace look like?

**Comment by dotnetchris** [comment]
I was attempting to communicate that line of XML over jabbr chat, the jabbr chat was attempting to create a clickable URL for http://localhost:8080 which it would error with "Invalid URI: Invalid port specified. ". This seems to be a bug in the auto parsing of URL text to become a clickable a tag.

**Comment by davidfowl** [comment]
I see, this was unclear from the bug descripton.

**Comment by admsteck** [comment]
I can work on this.  What would be the best way to handle this?  Have the link only point to http://localhost:8080....  ignore all uri's that point to localhost... try to ignore links that are contained in a connection string (perhaps look for the 'Url=' at the beginning)?

**Comment by davidfowl** [comment]
It's fixed already :).

**Comment by admsteck** [comment]
Ok
