### ISSUE TITLE
The operation has timed out in WPF

### ISSUE THREAD

**Issue by larrybeall** [JabbR/JabbR#401]
When using the Jabbr.Client with WPF I receive "The operation has timed out" exception every time I initialize a connection.  It does complete the signing process and either happens immediately after then or when a message is received.  The exact same code works fine in a console application.  If I force Long polling the client works fine.  You can find an example solution of the problem at the following link: http://larrybeall.net/files/WpfApplication1.zip .  When you start the wpf application, click connect and wait for the message box to get a sign in completed message.  At that time it should fail shortly there after.

**Comment by larrybeall** [comment]
Ugh.  Added this to the wrong repo.  David if you want me to move this over to the client repo let me know.

**Comment by davidfowl** [comment]
Yea move it over to the JabbR.Client.
