### ISSUE TITLE
special characters prevent interaction with different users

### ISSUE THREAD

**Issue by jsgoupil** [JabbR/JabbR#404]
I logged in with facebook an my nick was "JeanSébastien"
people were not able to message me privately, probably because of this é

**Comment by admsteck** [comment]
Looks like this is happening in Hubs/Chat.cs in the Send method.  It calls HtmlEncode on the message content which is turning "/msg JeanSébastien test" into "/msg JeanS&#233;bastien test"

**Comment by jsgoupil** [comment]
Github seems to encode what admsteck just said, but my email was not encoded.
The last part he said was
 "/msg JeanS& # 233;bastien test"
Without the space around #

Who is willing to open a bug on github now :)

**Comment by admsteck** [comment]
Should have looked a little closer at my comment after I sent it.  :)
