### ISSUE TITLE
Login doesn't complete using Google Chrome 17 or Firefox 8.

### ISSUE THREAD

**Issue by hellfirehd** [JabbR/JabbR#421]
The the OpenID popup appears and I choose one of the providers.  The provider's popup window appears, I auth successfully and it disappears.  The OpenID popup doesn't go away.  If I leave it long enough "There was an error contacting the server, please refresh in a few minutes." appears in another popup.

In Chrome I have tried it both in normal window and an incognito window with same results.  Same with FF8.  Works perfectly in IE9.

I don't think it is a provider issue since I get the same result with all of them.

**Comment by hellfirehd** [comment]
Have confirmed that this happens across different workstations.  Can anyone else reproduce?

**Comment by ntulip** [comment]
I assume you are talking about the following? http://i.imgur.com/HWnli.png

**Comment by hellfirehd** [comment]
Nope. That looks different than what I get.

**Comment by samandmoore** [comment]
odd... this works fine for me in FireFox 8 using my Google/Facebook/Twitter OpenIDs. What OpenID provider are you using, @Hellfire?

**Comment by ntulip** [comment]
i am using the default provider JanRain and using Google for the authentication.

**Comment by samandmoore** [comment]
@ntulip  I can reproduce _your_ error when I run the site locally... looking into it

**Comment by samandmoore** [comment]
@ntulip  were you running this locally or is this an issue you get on http://jabbr.net?

**Comment by ntulip** [comment]
I deployed it on an internal server at work.

**Comment by samandmoore** [comment]
alright so i think this is a janrain configuration issue because I can only get this bug to occur under those circumstances (locally running or running in some way that does not use jabbr.net as the host). I will look into it more when I have time to talk to @davidfowl  about more of the jabbr janrain configuration stuff. Unless someone has any other thoughts?

**Comment by ntulip** [comment]
Interesting. Please do let me know if there is a fix for this. Meanwhile we have a script that runs on page load which removes that overlay after they've logged in.
