### ISSUE TITLE
Messages post to the wrong room after opening from application shortcut

### ISSUE THREAD

**Issue by jeffhandley** [JabbR/JabbR#425]
This has happened to me twice.

**Repro steps:**
1. Have a Chrome application shortcut pinned to your taskbar, with a deep link into the nuget room.
2. Be a member of a private room.
3. Click the application shortcut.
4. Type a message and attempt to send it into the current room (nuget in my case).

**Expected:**
The message gets posted there.

**Actual:**
The message gets posted into the private room instead.

**Comment by samandmoore** [comment]
how does one create a Chrome application shortcut?

**Comment by samandmoore** [comment]
Alright I figured out how to create one of these shortcuts but I cannot manage to reproduce what you've mentioned above. @jeffhandley if you can still reproduce this then please let us know.

**Comment by jeffhandley** [comment]
Yes, I can still reproduce this using the exact steps in the bug.

**Comment by samandmoore** [comment]
weird! do you have to have both rooms open?

**Comment by jeffhandley** [comment]
More detailed repro steps:
1. Join a public room
2. Join a private room
3. Have no other rooms open
4. Create the application shortcut, pinned to the taskbar, so that it will start in the public room
5. Close all Chrome windows
6. Click on the application shortcut
   - The public room is loaded
   - The private room's tab is shown (don't navigate to it though)
7. Type a message into the public room and hit Enter
   - Nothing shows up in the public room
   - If you open the private room's tab, the message sent is shown, but nothing else - the private room didn't properly load
8. Refresh the browser
   - The private room loads
   - The message intended for the public room is also shown in the private room
9. Flip back to the public room
   - The message sent here is not shown

**Comment by samandmoore** [comment]
@jeffhandley hey, what version of chrome are you on?

**Comment by jeffhandley** [comment]
Presently, 19.0.1084.46 beta-m.  However, this issue has been happening for me since the introduction of private rooms, which I imagine was many versions prior on Chrome.

**Comment by samandmoore** [comment]
alright i finally repro'd this, i have no idea how, but it happened to me with 2 public rooms which makes me feel a bit more confident about solving it.

**Comment by davidfowl** [comment]
Does this still happen?

**Comment by samandmoore** [comment]
according to #507, this seems to be fixed.
