### ISSUE TITLE
Issue running jabbr locally

### ISSUE THREAD

**Issue by dannylloyd** [JabbR/JabbR#427]
I cloned the repo then ran it, and this is the error I got. 

Specs :
- Windows 7  
- SQL Express 2008 R2  
- Visual Studio 2010 SP1
### Error Message

Server Error in '/' Application.

There is no store type corresponding to the conceptual side type 'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of primitive type 'DateTimeOffset'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NotSupportedException: There is no store type corresponding to the conceptual side type 'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of primitive type 'DateTimeOffset'.

Source Error: 

Line 134:            // Only run migrations for SQL server (Sql ce not supported as yet)
Line 135:            var settings = new Settings();
Line 136:            var migrator = new DbMigrator(settings);
Line 137:            migrator.Update();
Line 138:        }

Source File: C:\Users\drlloyd.DIS\Documents\Visual Studio 2010\Projects\JabbR\JabbR\App_Start\Bootstrapper.cs    Line: 136 

Stack Trace: 

[NotSupportedException: There is no store type corresponding to the conceptual side type 'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of primitive type 'DateTimeOffset'.]
   System.Data.SqlClient.SqlProviderManifest.GetStoreType(TypeUsage edmType) +2600389
   System.Data.Entity.ModelConfiguration.Edm.Services.StructuralTypeMappingGenerator.MapTableColumn(EdmProperty property, DbTableColumnMetadata tableColumnMetadata, Boolean isInstancePropertyOnDerivedType, Boolean isKeyProperty) +97
   System.Data.Entity.ModelConfiguration.Edm.Services.PropertyMappingGenerator.Generate(EdmEntityType entityType, IEnumerable`1 properties, DbEntitySetMapping entitySetMapping, DbEntityTypeMappingFragment entityTypeMappingFragment, IList`1 propertyPath, Boolean createNewColumn) +1590
   System.Data.Entity.ModelConfiguration.Edm.Services.EntityTypeMappingGenerator.Generate(EdmEntityType entityType, DbDatabaseMapping databaseMapping) +653
   System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.GenerateEntityTypes(EdmModel model, DbDatabaseMapping databaseMapping) +166
   System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.Generate(EdmModel model) +68
   System.Data.Entity.ModelConfiguration.Edm.EdmModelExtensions.GenerateDatabaseMapping(EdmModel model, DbProviderManifest providerManifest) +70
   System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo) +206
   System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection) +264
   System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer) +308
   System.Data.Entity.Migrations.Extensions.DbContextExtensions.GetModel(DbContext context) +161
   System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationContext migrationContext, DbMigrationSet migrationSet) +303
   System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationContext migrationContext) +39
   JabbR.App_Start.Bootstrapper.DoMigrations() in C:\Users\drlloyd.DIS\Documents\Visual Studio 2010\Projects\JabbR\JabbR\App_Start\Bootstrapper.cs:136
   JabbR.App_Start.Bootstrapper.PreAppStart() in C:\Users\drlloyd.DIS\Documents\Visual Studio 2010\Projects\JabbR\JabbR\App_Start\Bootstrapper.cs:81

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks) +233
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +21
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +19
   WebActivator.BaseActivationMethodAttribute.InvokeMethod() +236
   WebActivator.ActivationManager.RunActivationMethods() +534
   WebActivator.ActivationManager.RunPostStartMethods() +41
   WebActivator.StartMethodCallingModule.Init(HttpApplication context) +125
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +418
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +300

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9775648
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +251

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.17379

**Comment by davidfowl** [comment]
What version of sql so you have installed?

Sent from my Windows Phone
From: dannylloyd
Sent: 3/29/2012 8:23 AM
To: David Fowler
Subject: [JabbR] Issue running jabbr locally (#427)
I cloned the repo then ran it, and this is the error I got.

Specs :
- Windows 7
- SQL Express 2008 R2
- Visual Studio 2010 SP1

###Error
Server Error in '/' Application.

There is no store type corresponding to the conceptual side type
'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of
primitive type 'DateTimeOffset'.

Description: An unhandled exception occurred during the execution of
the current web request. Please review the stack trace for more
information about the error and where it originated in the code.

Exception Details: System.NotSupportedException: There is no store
type corresponding to the conceptual side type
'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of
primitive type 'DateTimeOffset'.

Source Error:

Line 134:            // Only run migrations for SQL server (Sql ce not
supported as yet)
Line 135:            var settings = new Settings();
Line 136:            var migrator = new DbMigrator(settings);
Line 137:            migrator.Update();
Line 138:        }

Source File: C:\Users\drlloyd.DIS\Documents\Visual Studio
2010\Projects\JabbR\JabbR\App_Start\Bootstrapper.cs    Line: 136

Stack Trace:

[NotSupportedException: There is no store type corresponding to the
conceptual side type
'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of
primitive type 'DateTimeOffset'.]
   System.Data.SqlClient.SqlProviderManifest.GetStoreType(TypeUsage
edmType) +2600389
   System.Data.Entity.ModelConfiguration.Edm.Services.StructuralTypeMappingGenerator.MapTableColumn(EdmProperty
property, DbTableColumnMetadata tableColumnMetadata, Boolean
isInstancePropertyOnDerivedType, Boolean isKeyProperty) +97
   System.Data.Entity.ModelConfiguration.Edm.Services.PropertyMappingGenerator.Generate(EdmEntityType
entityType, IEnumerable`1 properties, DbEntitySetMapping
entitySetMapping, DbEntityTypeMappingFragment
entityTypeMappingFragment, IList`1 propertyPath, Boolean
createNewColumn) +1590
   System.Data.Entity.ModelConfiguration.Edm.Services.EntityTypeMappingGenerator.Generate(EdmEntityType
entityType, DbDatabaseMapping databaseMapping) +653
   System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.GenerateEntityTypes(EdmModel
model, DbDatabaseMapping databaseMapping) +166
   System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.Generate(EdmModel
model) +68
   System.Data.Entity.ModelConfiguration.Edm.EdmModelExtensions.GenerateDatabaseMapping(EdmModel
model, DbProviderManifest providerManifest) +70
   System.Data.Entity.DbModelBuilder.Build(DbProviderManifest
providerManifest, DbProviderInfo providerInfo) +206
   System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection) +264
   System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext
context, XmlWriter writer) +308
   System.Data.Entity.Migrations.Extensions.DbContextExtensions.GetModel(DbContext
context) +161
   System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationContext
migrationContext, DbMigrationSet migrationSet) +303
   System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationContext
migrationContext) +39
   JabbR.App_Start.Bootstrapper.DoMigrations() in
C:\Users\drlloyd.DIS\Documents\Visual Studio
2010\Projects\JabbR\JabbR\App_Start\Bootstrapper.cs:136
   JabbR.App_Start.Bootstrapper.PreAppStart() in
C:\Users\drlloyd.DIS\Documents\Visual Studio
2010\Projects\JabbR\JabbR\App_Start\Bootstrapper.cs:81

[TargetInvocationException: Exception has been thrown by the target of
an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[]
arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture,
Boolean skipVisibilityChecks) +233
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
+21
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +19
   WebActivator.BaseActivationMethodAttribute.InvokeMethod() +236
   WebActivator.ActivationManager.RunActivationMethods() +534
   WebActivator.ActivationManager.RunPostStartMethods() +41
   WebActivator.StartMethodCallingModule.Init(HttpApplication context) +125
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr
appContext, HttpContext context, MethodInfo[] handlers) +418
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state,
MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr
appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr
appContext) +300

[HttpException (0x80004005): Exception has been thrown by the target
of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9775648
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest
wr, HttpContext context) +251

Version Information: Microsoft .NET Framework Version:4.0.30319;
ASP.NET Version:4.0.30319.17379

---

Reply to this email directly or view it on GitHub:
https://github.com/davidfowl/JabbR/issues/427

**Comment by dannylloyd** [comment]
2008 Express R2

**Comment by davidfowl** [comment]
Strange, that should work just fine with DateTimeOffset.

**Comment by dannylloyd** [comment]
Programs and features shows that I have SQL 2005 installed also, could there be a conflict causing Visual Studio to use SQL 2005 instead of SQL 2008?

**Comment by davidfowl** [comment]
That must be the issue here. Maybe a bug in EntityFramework?

**Comment by dannylloyd** [comment]
I uninstalled SQL 2005 and reinstalled SQL 2008 and it is working now.

**Comment by Moantonio** [comment]
Error! Help me, please
There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.

Descripción: Excepción no controlada al ejecutar la solicitud Web actual. Revise el seguimiento de la pila para obtener más información acerca del error y dónde se originó en el código.

Detalles de la excepción: System.NotSupportedException: There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.

Error de código fuente:

Línea 24: // Only run migrations for SQL server (Sql ce not supported as yet)
Línea 25: var settings = new MigrationsConfiguration();
Línea 26: var migrator = new DbMigrator(settings);
Línea 27: migrator.Update();
Línea 28: }

: There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.]
System.Data.Entity.SqlServer.SqlProviderManifest.GetStorePrimitiveTypeIfPostSql9(String storeTypeName, String nameForException, PrimitiveTypeKind primitiveTypeKind) +210
System.Data.Entity.SqlServer.SqlProviderManifest.GetStoreType(TypeUsage edmType) +4269
System.Data.Entity.ModelConfiguration.Edm.Services.StructuralTypeMappingGenerator.MapTableColumn(EdmProperty property, String columnName, Boolean isInstancePropertyOnDerivedType) +141
System.Data.Entity.ModelConfiguration.Edm.Services.PropertyMappingGenerator.Generate(EntityType entityType, IEnumerable1 properties, StorageEntitySetMapping entitySetMapping, StorageMappingFragment entityTypeMappingFragment, IList1 propertyPath, Boolean createNewColumn) +1396
System.Data.Entity.ModelConfiguration.Edm.Services.TableMappingGenerator.Generate(EntityType entityType, DbDatabaseMapping databaseMapping) +721
System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.GenerateEntityTypes(DbDatabaseMapping databaseMapping) +189
System.Data.Entity.ModelConfiguration.Edm.Services.DatabaseMappingGenerator.Generate(EdmModel conceptualModel) +65
System.Data.Entity.ModelConfiguration.Edm.EdmModelExtensions.GenerateDatabaseMapping(EdmModel model, DbProviderInfo providerInfo, DbProviderManifest providerManifest) +73
System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo) +425
System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection) +103
System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext) +143
System.Data.Entity.Internal.RetryLazy2.GetValue(TInput input) +171 System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +590 System.Data.Entity.Internal.LazyInternalContext.get_ModelBeingInitialized() +31 System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer) +174 System.Data.Entity.Utilities.<>c__DisplayClass1.<GetModel>b__0(XmlWriter w) +40 System.Data.Entity.Utilities.DbContextExtensions.GetModel(Action1 writeXml) +163
System.Data.Entity.Utilities.DbContextExtensions.GetModel(DbContext context) +119
System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext) +882
System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration) +50
JabbR.Startup.DoMigrations(IJabbrConfiguration config) in c:\Users\Moises\Downloads\ejemplos signalR -web\JabbR-dev\JabbR-dev\JabbR\App_Start\Startup.Migrations.cs:26
JabbR.Startup.Configuration(IAppBuilder app) in c:\Users\Moises\Downloads\ejemplos signalR -web\JabbR-dev\JabbR-dev\JabbR\App_Start\Startup.cs:44

[TargetInvocationException: Se produjo una excepción en el destino de la invocación.]
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +92
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +108
System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +19
Owin.Loader.<>c__DisplayClass12.b__b(IAppBuilder builder) +118
Owin.Loader.<>c__DisplayClass1.b__0(IAppBuilder builder) +254
Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass2.b__0(IAppBuilder builder) +89
Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action1 startup) +892 Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action1 startup) +136
Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +159
System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func1 valueFactory) +115 System.Threading.LazyInitializer.EnsureInitialized(T& target, Boolean& initialized, Object& syncLock, Func1 valueFactory) +72
Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +104
System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +418
System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Se produjo una excepción en el destino de la invocación.]
System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9915300
System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
