### ISSUE TITLE
Silent logout makes for a confusing user experience

### ISSUE THREAD

**Issue by alastairs** [JabbR/JabbR#429]
Very often when using Jabbr, I won't explicitly log out, and will leave my room tabs open. As a result, my session times out at some point before I return and I am logged out automatically. 

Unfortunately, there is no indication that I have been logged out automatically, other than my name no longer appears in the Online Users list in any particular room. I feel this is too subtle a feedback mechanism given that Jabbr doesn't seem to work without being logged in. It's not until I go back to the lobby and type /login that it's confirmed to me that I was logged out; up until that point, I'm working on an assumption. 

A more explicit indication of a user's state would make this much clearer, e.g., a message box indicating I have been logged out (perhaps with a five minute countdown), and a message in the lobby (displayed in something other than grey) saying "Welcome back <username>" or "Welcome guest. Type '/login' to login."

**Comment by davidfowl** [comment]
We'll look into this. Try the latest version and see if it still happens. Does your machine go to sleep at any point?

**Comment by alastairs** [comment]
On some machines, yes I do put them to sleep. That's not the only case, though, and it would be useful if JabbR could handle that situation (if technically feasible).

**Comment by davidfowl** [comment]
This was fixed.
