### ISSUE TITLE
JabbR.Net does not work on iPad

### ISSUE THREAD

**Issue by jchannon** [JabbR/JabbR#430]
When browsing to Jabbr.Net on iPad the page never loads fully and looking in the debug console I get various errors:

JavaScript Error TypeError: 'undefined' is not an object

NOT_FOUND_ERR_DOM: Exception 8 An attempt was made to reference a Node in a context where it does not exist

Here's a screenshot https://twitter.com/#!/jchannon/status/187475450514243584/photo/1

This was found on a British language iPad using 5.1 iOS

**Comment by antonsw** [comment]
+1
