### ISSUE TITLE
Unable to claim username from before twitter/facebook/openid auth integration

### ISSUE THREAD

**Issue by programatt** [JabbR/JabbR#445]
Not a huge deal, but I started using jabbr.net without logging in through a 3rd party service, so now when I login with my twitter account, it states that my name is MathewRPhillips1 instead of MathewRPhillips and I am unable to /nick MathewRPhillips <password> to claim it.

**Comment by davidfowl** [comment]
This isn't a bug, there's no way for jabbr to know that you're google account matches your facebook account etc. Log in and send me a /msg and I can help here
