### ISSUE TITLE
Page title not updated

### ISSUE THREAD

**Issue by quentez** [JabbR/JabbR#450]
When you switch to Jabbr from another tab on Google Chrome, the title is not updated to reflect that you just read some messages.

This is a problem I experienced with other apps and the solution was to delay the title update with a `setTimeout` (100ms worked fine for me).

**Comment by samandmoore** [comment]
looks like this is a bug in chrome... I'm going to try this solution later:

http://stackoverflow.com/questions/2952384/changing-the-window-title-when-focussing-the-window-doesnt-work-in-chrome
