### ISSUE TITLE
Loading Animation when sending message should be remove

### ISSUE THREAD

**Issue by rpgmaker** [JabbR/JabbR#455]
Rather than showing animation when sending message. It should show the message as it is and assume that the receivers already receive it. And in a case where the message fails to send, then a red text or some kinda of alert should be display notifying the sender that the message could not be delivered.

**Comment by davidfowl** [comment]
I don't agree that we should implement this but I'l give it a few days to see if anyone else cares about it.

**Comment by rpgmaker** [comment]
It would be a nice to have :)

**Comment by davidfowl** [comment]
Ok so this isn't going to happen as the current behavior is nice if jabbr slows down. Besides you shouldn't see this anymore  :smile:
