### ISSUE TITLE
URL detection fails to catch URL with ...

### ISSUE THREAD

**Issue by half-ogre** [JabbR/JabbR#459]
Try pasting this into a chat window: https://github.com/NuGet/NuGetGallery/compare/345ea25491...90a05bc3e0

**Comment by samandmoore** [comment]
we have to tweak the regexp here:

https://github.com/davidfowl/JabbR/blob/master/JabbR/Infrastructure/TextTransform.cs#L47

that's a beast.

**Comment by samandmoore** [comment]
I have to add a test for it, but this regex should work:

`@"(?i)(?<s>(?:https?|ftp)://|www\.)?(?:\S+(?::\S*)?@)?(?:(?:[\w\p{S}][\w\p{S}@-]*[.:])+\w+)(?(s)/?|/)(?:(?:[^\s()<>,\u0022'”]+|[,\u0022'”][^\s()<>,\u0022]|\((?:[^\s()<>]+|(?:\([^\s()<>]+\)))*\))*)"`
