### ISSUE TITLE
Enhancements for /help

### ISSUE THREAD

**Issue by samandmoore** [JabbR/JabbR#460]
We need to build a better /help command; it is getting too large and unstructured. Suggestion:

```
/help
  * /nick
  * /join
  * /create
  * /flag
  * /help --commands
  * /help --features
```

this format would provide a simple scan-able help section for newcomers and provide an easy way to get at the rest of the commands for the power-users. It also starts us on a nice path for building a fully-structured man pages style help.

**Comment by davidfowl** [comment]
And put it on a modal dialog.

**Comment by samandmoore** [comment]
@davidfowl you want to move it to a modal?

so `/help` would trigger a modal to popup and not display in the chat window?

**Comment by davidfowl** [comment]
Yep

Sent from my Windows Phone

**Comment by samandmoore** [comment]
I'm envisioning something like the shift+? thing that pops up on github for the new help... modal with nice styling, and the contents of the help dialog can be powered by MEF. i.e. we can fill in the command attributes on the different commands with the descriptions and then use MEF to load them all into a list which we can render in this dialog :)

**Comment by hnrkndrssn** [comment]
I'm working on this

**Comment by cmaish** [comment]
This looks pretty done to me.  If anyone thinks that more work needs to be done here, comment and we'll reopen.
