### ISSUE TITLE
Admin / God-mode

### ISSUE THREAD

**Issue by samandmoore** [JabbR/JabbR#461]
We need to add some admin features

features:
1. Admins can perform any owner operations on any room
2. Admins can delete messages (special UI triggered by pressing tilde key, `, shows a message selection tool in room

required changes:
1. add an `IsAdmin` bit field to the users table.
2. cmds (granting/revoking) admin access
3. change all operations that require room owner to add `|| IsAdmin`
4. ensure that no one can perform action (kick/unallow) on admin unless they are admin
5. `/ban` command, bans user via some sort of bit field in the ChatUser table? via IP? via what?
6. `/broadcast` messages all rooms

**Comment by samandmoore** [comment]
add these new commands to the ever-growing help section

**Comment by samandmoore** [comment]
still to do:
1. Admins can delete messages (special UI triggered by pressing tilde key, `, shows a message selection tool in room
2. `/ban` command, bans user via some sort of bit field in the ChatUser table? via IP? via what?

**Comment by davidfowl** [comment]
We should figure out if we ban per room also. Maybe there's different levels of granularity...
