### ISSUE TITLE
The "/rooms" command is slow and becoming useless

### ISSUE THREAD

**Issue by jeffhandley** [JabbR/JabbR#470]
When Jabbr first started, the /rooms command was extremely useful.  Now, not so much.  It takes a handful of seconds to get the list, and then it's really hard to actually find rooms in the list.

For instance, the other day I wanted to see what rooms there were for "ASP.NET MVC," and running "/rooms" provided me with an unsorted list with lots of empty rooms.  What I really wanted was to type:

/rooms mvc

And as a result see all rooms that have "mvc" in their name, with them grouped by rooms with people online and without, and then sorted alphabetically within those groups.

**Comment by davidfowl** [comment]
+1
