### ISSUE TITLE
Adjust JabbR web app to be able to run on OWIN web servers

### ISSUE THREAD

**Issue by loudej** [JabbR/JabbR#478]
Not exactly sure how much work would be involved, but would be nice if the web app had a Startup class and could be hosted on servers like Kayak, Firefly, or HttpListener

**Comment by davidfowl** [comment]
So the bootstrapper class?

**Comment by samandmoore** [comment]
well, wouldn't this require a complete removal of our dependency on System.Web?

**Comment by davidfowl** [comment]
Would be nice to go through and figure out what the hard dependencies are. I know we have:
- HttpHandlers
- PreApplicaitionStart

**Comment by samandmoore** [comment]
- HttpUtility (which i think can be swapped out somewhere)

**Comment by loudej** [comment]
PreApplicationStart seems okay - it's a public static that can be called from the Startup class when outside asp.net

First dependency within PreApplicationStart was something like a call to ToAbsolutePath.

Also looks like OWIN will need a simple way to run server-side pages (default.aspx specifically) - would a cshtml page work as well there? That might be an easier kind of file to execute in a self-hosted owin context like katana.

**Comment by davidfowl** [comment]
cshtml is fine. There's more you have to worry about though, like the WebApi controller I just added, and the Auth.ashx (which can be replaced, but with what?)

**Comment by loudej** [comment]
well, let's see...

WebApi already has an owin adapter, so that shouldn't be a problem at all... just need to make sure that fwk is also spun up in the startup class

Auth.ashx is supported directly by asp.net... Could the work it does be pulled out into a host-agnostic method that auth.ashx calls? That way the request could be routed to that host-agnostic method from auth.ashx on asp.net, and by other means on owin?

**Comment by davidfowl** [comment]
I'm working on this right now in the portable branch.

**Comment by davidfowl** [comment]
Done
