### ISSUE TITLE
Chrome Update Gave Exception

### ISSUE THREAD

**Issue by keroger2k** [JabbR/JabbR#489]
I was in a chat room when I did my google chrome update.  When it restarted by itself Jabbr came up with the following message.

[InvalidOperationException: Bad response from login provider.]
   JabbR.Auth.Login.ProcessRequest(HttpContext context) in c:\dev\github\JabbR\JabbR\Auth\Login.ashx.cs:55
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +625
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +270

Thought I'd share....

**Comment by davidfowl** [comment]
Does it happen consistently?

**Comment by keroger2k** [comment]
It has only happened once for me.  It wasn't a big deal, just thought you might be interested to know.  The next Chrome update I can test it out.

**Comment by davidfowl** [comment]
ok
