### ISSUE TITLE
Login doesn't work on Chrome

### ISSUE THREAD

**Issue by jpoehls** [JabbR/JabbR#492]
It works for me in Firefox and Opera but fails everytime in Chrome.

What happens:
1. Jabbr.net loads and shows the dialog with login options
2. Clicking an option will open a popup to authenticate.
3. After completing the authentication steps in the popup window, the popup closes but Jabbr.net never changes. i.e. it still shows the dialog with login options.

Here's a screencast of that. http://www.screencast.com/t/49tZIVS1wZ

This happens both on my Windows machine at work and on my Mac at home. Both Chrome.

The only difference is that at home (on the Mac) it will usually refresh the JabbR page after step 3, but it just shows the same login options dialog right away. It appears to be _trying_ to log me in but never does.

I watched the network activity in Chrome and this is the last response that came in after the authentication popup closed. https://gist.github.com/2709843

**Comment by jpoehls** [comment]
I should note that I also tested this with all of my extensions disabled.

**Comment by samandmoore** [comment]
Hey @jpoehls what version of chrome are you on?

**Comment by jpoehls** [comment]
19.0.1084.46 beta on both machines. I know this has been happening consistenly since at least 18 beta.

**Comment by samandmoore** [comment]
hmm, I am on 16.0.912.75 m (stable) and I have no issues so I suspect it has something to do with chrome. Does it work for you in another browser?

**Comment by jpoehls** [comment]
I just switched to Chrome 19.0.1084.46 stable (instead of beta, but apparently they are the same release right now) and of course had the same problem. I'm sure it is a Chrome thing since it works in Firefox and Opera.

**Comment by cbley** [comment]
I've seen this behavior when third-party cookies are disabled. Check that setting in your Chrome

**Comment by jpoehls** [comment]
@cbley Thank you! This appears to have been the problem. Bit frustrating, but at least I know what the deal is.
