### ISSUE TITLE
[req] Verbose connection lost messages

### ISSUE THREAD

**Issue by AlecTaylor** [JabbR/JabbR#496]
Can you add in verbose connection lost messages?

I often lose connection, and on IRC it just automatically rejoins channels and whatnot (but shows that it was disconnected).

With JabbR I need to press Ctrl+R when I guess that I have missed new replies. That's right, I said "guess".

Could you please add in verbose connection loss messages with a reload javascript link?

Thanks,

Alec Taylor

**Comment by davidfowl** [comment]
How did you get disconnected? Did you lose connectivity? We generally retry forever but if you computer went asleep or something I'm not sure what the expected behavior is.

**Comment by AlecTaylor** [comment]
I'm sure there are a set number of retry attempts that my lossy connection went over.

So it would be good to have a "connection lost" message so that I know to refresh the chat window.

**Comment by samandmoore** [comment]
this should be resolved when #500 is implemented.
