### ISSUE TITLE
External link to new instance incorrectly sets focused room

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#507]
When entering JabbR via an external link to a room the room is visible however the active room isn't being set properly. Without changing rooms and typing a message that message ends up going to the room the user was last in and not the new room opened via the link.

Example:
I entered a room (say #trivia) i closed the browser, clicked on a link to take me to #aspnetmvc and while #aspnetmvc was visible the messages i type were being posted in #trivia instead.

**Comment by samandmoore** [comment]
i think this is related / the same issue as #425

**Comment by davidfowl** [comment]
Does this still happen?

**Comment by Buildstarted** [comment]
It doesn't appear to be an issue any more
