### ISSUE TITLE
give /me a more prominent colour

### ISSUE THREAD

**Issue by adamralph** [JabbR/JabbR#508]
A /me should be in a more prominent colour - at the moment they look just like a 'user left chat' and it's not easy to see the distinction.

A popular choice in other messaging clients (e.g. mIRC) seems to be purple.

**Comment by adamralph** [comment]
I'm going to implement this, since no-one else seems interested in doing so ;-)

**Comment by samandmoore** [comment]
that's open source, buddy :smile:

---

Sam Moore
908.625.1108
everywhere: samandmoore
