### ISSUE TITLE
add location flag alongside nationality flag

### ISSUE THREAD

**Issue by adamralph** [JabbR/JabbR#510]
I am British, living in Switzerland. I'd like to have two flags - one showing my nationality and another showing my location.

**Comment by davidfowl** [comment]
I think this'll be confusing

**Comment by samandmoore** [comment]
I agree, seems unnecessary

**Comment by PureKrome** [comment]
Just use the /note ? Pom living in Switzerland? (and have the UK flag next to your name..?)

**Comment by adamralph** [comment]
@davidfowl @samandmoore fair enough - I'll close

@PureKrome not a bad idea, thanks
