### ISSUE TITLE
Rooms don't load in IE 10.

### ISSUE THREAD

**Issue by RyannosaurusRex** [JabbR/JabbR#511]
In IE 10, no rooms are loaded in the right navigation bar, and no tabs are fully loaded (including the Lobby tab), which means there is no way to use JabbR in IE 10.

**Comment by samandmoore** [comment]
fixed in 23a3b015ad65e7b19904f814f586ce7d5e9767b3 by setting IE10 to use IE9 mode. this will probably need a different fix somewhere down the line because of a bug in Twitter Bootstrap.
