### ISSUE TITLE
Gravatar hover preview effect

### ISSUE THREAD

**Issue by timbjames** [JabbR/JabbR#516]
Hi Mr Fowler,

I think a nice little feature that could easily be added to the UI, is a hover preview of a users Gravatar image.

Basic coding which works is;

$('.gravatar').hover(function(){  
    var $g = $(this);
    $g.attr('src', $g.attr('src').replace('s=16','s=80'));
 }, 
function(){ 
    var $g = $(this);
    $g.attr('src', $g.attr('src').replace('s=80','s=16')); 
});

**Comment by samandmoore** [comment]
where would this go? do you have a screenshot?

**Comment by timbjames** [comment]
Best just try it out yourself. Paste the code into Google Chromes Console while on Jabbr. Then hover over a user's Gravatar image.

**Comment by ElliotWood** [comment]
I like it....:)

Action: Hovered over the gravatar.
Result:
<a href="http://s971.photobucket.com/albums/ae193/gigaflare_elliot/?action=view&amp;current=gravs80.png" target="_blank"><img src="http://i971.photobucket.com/albums/ae193/gigaflare_elliot/gravs80.png" border="0" alt="Photobucket"></a>

**Comment by timbjames** [comment]
I would like to add this feature to JabbR.

**Comment by 0vermind** [comment]
+1

**Comment by hnrkndrssn** [comment]
In dev and will be available in the next release
