### ISSUE TITLE
Unable to login in IE 10

### ISSUE THREAD

**Issue by thedalewilliams** [JabbR/JabbR#517]
The grey background for the light box appears but the login dialog doesn't pop down as expected.

**Comment by lambda125** [comment]
yep, +1 on this. It doesn't work on IE10 desktop mode on Windows 8 for me.

**Comment by samandmoore** [comment]
fixed in 23a3b015ad65e7b19904f814f586ce7d5e9767b3 by setting IE10 to use IE9 mode. this will probably need a different fix somewhere down the line because of a bug in Twitter Bootstrap.
