### ISSUE TITLE
Urban Dictionary Command Provider

### ISSUE THREAD

**Issue by phillip-haydon** [JabbR/JabbR#518]
The ability to type:

/urban [word]

And have the first result of urban dictionary embedded into the chat. 

Possibly include #

/urban [word] [entry #]

To embed a certain entry in urban dictionary.

**Comment by WilliamBZA** [comment]
Don't think it makes sense to have this as a command, should rather be a ContentProvider.

I've knocked up a sample here: https://github.com/WilliamBZA/JabbR/blob/master/JabbR/ContentProviders/UrbanDictionaryContentProvider.cs

**Comment by phillip-haydon** [comment]
When I wrote the issue I think I meant Content Provider but I was probably suffering from lack of caffeine :)
