### ISSUE TITLE
Pluginsystem for Contentprovider

### ISSUE THREAD

**Issue by schulz3000** [JabbR/JabbR#522]
I suggest a pluginsystem for the contentproviders.
If you run JabbR on a live system then you can add a dll for a new contentprovider or if there's an update for an existing one then you only must update this dll and you have not to deploy the whole application.
I think implementation can be done on an easy way with MEF for example.

Also give an admin the possibility to enable or disable contentprovider.

**Comment by davidfowl** [comment]
Sounds like an awesome pull request.

**Comment by hnrkndrssn** [comment]
Done in #1078
