### ISSUE TITLE
IIS6 Configuration for SignalR

### ISSUE THREAD

**Issue by gurralapraveen** [JabbR/JabbR#523]
I am working with SignalR in my visual studio it is working fine 
But when i am deploying the same application in iis6 server 
It is throwing the following errors
-> Internal Server Error SignalR/hubs

-> start(anonymous type) Error

-> can not start signalr/hubs

etc..,

can you tell me how to configure IIS6 in order to run the SignalR application

thank you,

**Comment by davidfowl** [comment]
This is the JabbR project file this issue on the SignalR repository,
