### ISSUE TITLE
A Snap web handler threw an exception. (on login attempt)

### ISSUE THREAD

**Issue by michaelmcdaniel** [JabbR/JabbR#529]
logging in using google account.

A Snap web handler on host haskell1-prod.engage-cloud.com threw an exception. Details:
HandshakeFailed Error_EOF
HTTP Request:
 GET jabbr.rpxnow.com:0/openid/start?language_preference=en&token_url=http%3A%2F%2Fjabbr.net%2FAuth%2FLogin.ashx%3Fhash%3D&display=popup&widget=true&openid_identifier=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid&origin_url=http%3A%2F%2Fjabbr.net%2F&provider_name=google&force_reauth=false&xdReceiver=https%3A%2F%2Fjabbr.rpxnow.com%2Fxdr&callback=none&widget_type=auth&token_action=url?language_preference=en&token_url=http%3A%2F%2Fjabbr.net%2FAuth%2FLogin.ashx%3Fhash%3D&display=popup&widget=true&openid_identifier=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid&origin_url=http%3A%2F%2Fjabbr.net%2F&provider_name=google&force_reauth=false&xdReceiver=https%3A%2F%2Fjabbr.rpxnow.com%2Fxdr&callback=none&widget_type=auth&token_action=url User-Agent[Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11]
Headers:
fromList [("Accept",["text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8"]),("Accept-Charset",["ISO-8859-1,utf-8;q=0.7,*;q=0.3"]),("Accept-Encoding",["gzip,deflate,sdch"]),("Accept-Language",["en-US,en;q=0.8"]),("Cookie",["welcome_info=%5B%22welcome_user%22%2C%7B%22name%22%3A%22Michael+McDaniel%22%7D%5D; welcome_info_name=Michael+McDaniel; openid_expected_tab=; expected_tab=; expected_user_input=; origin_url="]),("Host",["jabbr.rpxnow.com"]),("Referer",["http://jabbr.net/"]),("User-Agent",["Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11"]),("X-Forwarded-For",["XXX.XXX.XXX.XXX"]),("X-Forwarded-Port",["443"]),("X-Forwarded-Proto",["https"])]

(IP address removed...)

**Comment by davidfowl** [comment]
What browser?
Do you have a browser plugin that might have caused this?

**Comment by michaelmcdaniel** [comment]
Chrome: 20.0.1132.47 m
No plugins.

As a side note, I refreshed the page/popup window (by right mouse click - reload) and it then worked as expected.

**Comment by davidfowl** [comment]
Shouldn;t happen anymore
