### ISSUE TITLE
Incorrect URL rendering

### ISSUE THREAD

**Issue by dpatti** [JabbR/JabbR#537]
Three instances of common url uses that I found do not render correctly.

```
"Visit http://www.jabbr.net/"
(Find us at http://www.jabbr.net/)
https://www.google.com/search?q=test+search&sugexp=chrome,mod=14&sourceid=chrome&ie=UTF-8
```

As you would expect, the trailing quote and parenthesis are not part of the URL themselves. Of course, there are plenty of urls (such as those used by Wikipedia) where parenthesis are present. You could consider trying a more thorough regex, such as the one at [Daring Fireball](http://daringfireball.net/2010/07/improved_regex_for_matching_urls). 

For the third, it looks like the ampersands are getting escaped as `&amp;` when they should not at all. Similarly, quotes are being escaped as `&quot;` when it should be `%22`, and so forth.

I took a stab at fixing this myself, but not really being familiar with the various encoding methods used I couldn't find a good solution that passed unit tests and showed positive results in actual testing.

**Comment by WilliamBZA** [comment]
The last one seems to be working. I copy-pasta'd it and navigated to it just fine. That one may have already been resolved.

The first example doesn't render as a URL while the second does, but it includes the closing bracket.

**Comment by dpatti** [comment]
The third one was indeed fixed in #569.

**Comment by davidfowl** [comment]
The url rendering really sucks, I needs an extreme make over.

**Comment by samandmoore** [comment]
+1

**Comment by davidfowl** [comment]
This shoud be fixed now.
