### ISSUE TITLE
closed rooms should be listed at the bottom of lobby list

### ISSUE THREAD

**Issue by samandmoore** [JabbR/JabbR#539]
closed rooms should list at the bottom of the list of rooms in the lobby AND there needs to be UI elements for hiding them completely.

**Comment by davidfowl** [comment]
you did 1/2 of this

**Comment by samandmoore** [comment]
The other half is in progress. I just don't like that the lobby uses the
user lists to display the rooms so I was trying to come up with a better
solution.
On Jul 31, 2012 11:37 PM, "David Fowler" <
reply@reply.github.com>
wrote:

**Comment by samandmoore** [comment]
here are some images for how it looks right now:

### Default View in Lobby

![Default View in Lobby](http://www.pasteshack.net/images/073115001343836638.png)

### Lobby showing Closed Rooms

![Lobby showing Closed Rooms](http://www.pasteshack.net/images/710767001343836664.png)

### Lobby showing Closed Rooms while Searching

![Lobby showing Closed Rooms while Searching](http://www.pasteshack.net/images/393254001343836694.png)

### Lobby NOT showing Closed Rooms while Searching

![Lobby showing while Searching](http://www.pasteshack.net/images/570359001343836713.png)

things to consider:
- when a new closed room is created that it is visible/invisible depending on current setting in lobby
- when livesearch happens, closed rooms only show up if they MATCH and are supposed to be VISIBLE

**Comment by davidfowl** [comment]
That's not sexy that all but I can live with it.

**Comment by samandmoore** [comment]
@davidfowl OH, well then! I was going for function over form for now. I didn't know it had to be sexy! let's see if i can hike up its skirt a bit.
