### ISSUE TITLE
Jabbr/Jabbr.net doesn't load on Opera on Mac / Windows

### ISSUE THREAD

**Issue by chrisntr** [JabbR/JabbR#540]
Jabbr.net fails to load using Opera: looking like the following - http://screencast.com/t/RqUvIWzV

**Comment by samandmoore** [comment]
can you check opera using their console or firebug for some sort of error message?

**Comment by samandmoore** [comment]
(i'm guessing it has to do with Janrain, the openid provider we're using)

**Comment by chrisntr** [comment]
There seems to be three JavaScript error messages, doesn't look like Janrain: http://screencast.com/t/VEjFXtSZT

**Comment by davidfowl** [comment]
We're nuking janrain in favor of a custom auth solution.

**Comment by davidfowl** [comment]
Try it again now it's likely fixed.
