### ISSUE TITLE
Closing the room tab calls roomClose

### ISSUE THREAD

**Issue by nschonni** [JabbR/JabbR#548]
The old close function was renamed, and now conflicts with this event name called here https://github.com/davidfowl/JabbR/blob/master/JabbR/Chat.ui.js#L832

This causes a JS error when leaving a room "Error: Unable to get value of the property 'toLowerCase': object is null or undefined"

**Comment by samandmoore** [comment]
fixed by namespacing the events in 8943b75a1d10cecc78ffda7da15158a9a10f83b3
