### ISSUE TITLE
Add Client Side Logging

### ISSUE THREAD

**Issue by nschonni** [JabbR/JabbR#553]
JabbR needs additional logging on the client side to be able to troubleshoot hard to repo client side bugs.
One possible implementation would be to hook into the SignalR received function:

> $.connection.hub.received(function(data) { $.connection.hub.log(JSON.strigify(data)) }) 

This would be very noisy, so logging levels or opting in to logging certain types of events will probably be required.

**Comment by samandmoore** [comment]
Good idea. I have a branch in progress for this. Its called js-logging.
Check it out before you work on anything.
On Jul 27, 2012 4:20 PM, "Nick Schonning" <
reply@reply.github.com>
wrote:

**Comment by samandmoore** [comment]
useful library we should look into integrating: http://benalman.com/projects/javascript-debug-console-log/

**Comment by davidfowl** [comment]
This works today with cookies $.cookie('jabbr.logging', '1', {expires:30})
