### ISSUE TITLE
on-load away users should be faded

### ISSUE THREAD

**Issue by samandmoore** [JabbR/JabbR#558]
when you load a room or log-on, the user list should show away users as grayed out.

this behavior should mimic what happens when a user goes from active to away while you are online.

**Comment by samandmoore** [comment]
need to repurpose this https://github.com/davidfowl/JabbR/blob/master/JabbR/Chat.ui.js#L1339

**Comment by WilliamBZA** [comment]
Should be sorted with PR: https://github.com/davidfowl/JabbR/pull/591
