### ISSUE TITLE
Allow re-ordering of room tabs

### ISSUE THREAD

**Issue by devuxer** [JabbR/JabbR#575]
It would be nice to be able to reorder room tabs by dragging and dropping them, just as you can with Visual Studio, Firefox, etc.

**Comment by cmaish** [comment]
This is now in dev and should find its way to prod soon.

**Comment by devuxer** [comment]
Great, but does it work in Firefox? Dragging the tabs seems to have no effect for me.

**Comment by cmaish** [comment]
It's going to get to prod the next time a deployment gets made (prod is currently running https://github.com/JabbR/JabbR/commit/6656332d887ee81a1f7decd47e1f022196211d28 which is older than the changes).  

If you've got a copy of the dev branch up and running and are experiencing the issue, we may need to reopen this, but it should work in firefox (at least it does in staging against FF 22.0).

**Comment by devuxer** [comment]
Ahh of course. Closed doesn't mean deployed :)

I don't have a copy of the dev branch running, so no bug that I know of.
