### ISSUE TITLE
"No users" missing under Online and Owners headings

### ISSUE THREAD

**Issue by nschonni** [JabbR/JabbR#580]
When a user changes from Online to Away, or an Owner leaves a room, the "No Users" message should be shown if there are no other users under that section. It appears the function that adds the No User message https://github.com/davidfowl/JabbR/blob/master/JabbR/Chat.ui.js#L301 is not invoked.

**Comment by WilliamBZA** [comment]
Should be sorted with PR: https://github.com/davidfowl/JabbR/pull/591
