### ISSUE TITLE
IE 8.0.6001.18702 on Windows XP does not connect

### ISSUE THREAD

**Issue by vegardlarsen** [JabbR/JabbR#584]
On a fresh install of Windows XP SP3, upgraded to IE8.0.6001.18702 (which is the latest IE8 version for WinXP), you cannot connect ot Jabbr. After signing in, the following two errors are listed:

```
'length' is not null or not an object
Line: 2
JabbR_1_2E7505DF97556B006375FF8A746F573C.js

Exception thrown and not caught
Line: 6, Char: 213
engage_signin.js
Code: 0
URI: http://widget-cdn.rpxnow.com/js/lib/engage_signin.js?version=2012.2_rc6
```

After this typing `/?` results in a reload of the page.

After firing up Developer Tools and starting debugging, it gets a bit further, and can display the tabs of joined rooms, but no rooms can be selected, and it keeps throwing an exception on line 6, column 213 in `engage_signin.js`.

**Comment by davidfowl** [comment]
Janrain is being removed for login and custom auth is being built so this should all go away.
