### ISSUE TITLE
Running jabbr locally issue: There is no store type corresponding to the conceptual side type 'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of primitive type 'DateTimeOffset'.

### ISSUE THREAD

**Issue by raghav-axero** [JabbR/JabbR#588]
Hi,

On running the project (master of https://github.com/davidfowl/JabbR) I am getting

There is no store type corresponding to the conceptual side type 'Edm.DateTimeOffset(Nullable=True,DefaultValue=,Precision=)' of primitive type 'DateTimeOffset'. I am running it on WIndows7, VS2012 with SQL Server 2008 installed on my machine. Am I missing something?

**Comment by davidfowl** [comment]
Did you uninstall sql 2005?

**Comment by raghav-axero** [comment]
Hmm.. I see SQL 2005 installed on my machine. Let me uninstall it and get back you. Thanks for your reply David.

**Comment by raghav-axero** [comment]
It worked and moved ahead and now I got:

"An error occurred while getting provider information from the database. This can be caused by Entity Framework using an incorrect connection string. Check the inner exceptions for details and ensure that the connection string is correct."

**Comment by samandmoore** [comment]
@raghav-khunger did you check the inner exception? can you give us the details?

**Comment by Moantonio** [comment]
There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.

Descripción: Excepción no controlada al ejecutar la solicitud Web actual. Revise el seguimiento de la pila para obtener más información acerca del error y dónde se originó en el código. 

Detalles de la excepción: System.NotSupportedException: There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.

Error de código fuente: 

Línea 25:             var settings = new MigrationsConfiguration();
Línea 26:             var migrator = new DbMigrator(settings);
Línea 27:             migrator.Update();
Línea 28:         }
Línea 29:     }

Archivo de origen: c:\Users\Moises\Downloads\ejemplos signalR -web\JabbR-dev\JabbR-dev\JabbR\App_Start\Startup.Migrations.cs    Línea: 27 

Seguimiento de la pila: 

[NotSupportedException: There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.]
   System.Data.Entity.SqlServer.SqlProviderManifest.GetStorePrimitiveTypeIfPostSql9(String storeTypeName, String nameForException, PrimitiveTypeKind primitiveTypeKind) +208
   System.Data.Entity.SqlServer.SqlProviderManifest.GetStoreType(TypeUsage edmType) +4269
   System.Data.Entity.Migrations.Model.ColumnModel.IsNarrowerThan(ColumnModel column, DbProviderManifest providerManifest) +190
   System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.BuildAlterColumnOperation(String table, XElement targetProperty, String targetEntitySetName, ModelMetadata targetModelMetadata, XElement sourceProperty, String sourceEntitySetName, ModelMetadata sourceModelMetadata) +190
   System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.<FindChangedColumns>b__260(<>f__AnonymousType46`2 <>h__TransparentIdentifier254) +361
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +145
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +381
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(ModelMetadata source, ModelMetadata target, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator) +493
   System.Data.Entity.Migrations.Infrastructure.EdmModelDiffer.Diff(XDocument sourceModel, XDocument targetModel, Lazy`1 modificationCommandTreeGenerator, MigrationSqlGenerator migrationSqlGenerator) +666
   System.Data.Entity.Migrations.DbMigrator.IsModelOutOfDate(XDocument model, DbMigration lastMigration) +95
   System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) +368
   System.Data.Entity.Migrations.Infrastructure.MigratorBase.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) +59
   System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration) +887
   System.Data.Entity.Migrations.<>c__DisplayClassc.<Update>b__b() +38
   System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) +369
   System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) +42
   System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) +136
   System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update() +33
   JabbR.Startup.DoMigrations(IJabbrConfiguration config) in c:\Users\Moises\Downloads\ejemplos signalR -web\JabbR-dev\JabbR-dev\JabbR\App_Start\Startup.Migrations.cs:27
   JabbR.Startup.Configuration(IAppBuilder app) in c:\Users\Moises\Downloads\ejemplos signalR -web\JabbR-dev\JabbR-dev\JabbR\App_Start\Startup.cs:44

[TargetInvocationException: Se produjo una excepción en el destino de la invocación.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +92
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +108
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +19
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +118
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +254
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass2.<InitializeBlueprint>b__0(IAppBuilder builder) +89
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +892
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +136
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +159
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
   System.Threading.LazyInitializer.EnsureInitialized(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +72
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +104
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +418
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Se produjo una excepción en el destino de la invocación.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9915300
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254

Información de versión: Versión de Microsoft .NET Framework:4.0.30319; Versión ASP.NET:4.0.30319.18446

**Comment by davidfowl** [comment]
What database are you using?

**Comment by Moantonio** [comment]
SQL Server 2008 R2

**Comment by Moantonio** [comment]
![image](https://cloud.githubusercontent.com/assets/8619642/4113155/c923f54c-3245-11e4-9789-0423ff713e56.png)

these are the components that I have sql 2005 uninstall a component of these and I came out error starting the project solution. But I went back to install for me not to leave the error! It has to do with the type 'DateTimeOffset'

**Comment by davidfowl** [comment]
Sounds like you need to update that database to one that supports DateTimeOffset. Either that or update your local jabbr to use DateTime instead of DateTimeOffset.

**Comment by Moantonio** [comment]
mmmm... use DateTime instead of DateTimeOffset.Generates another error

There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.

Descripción: Excepción no controlada al ejecutar la solicitud Web actual. Revise el seguimiento de la pila para obtener más información acerca del error y dónde se originó en el código. 

Detalles de la excepción: System.NotSupportedException: There is no store type corresponding to the conceptual side type 'DateTimeOffset' of primitive type 'DateTimeOffset'.

Error de código fuente: 

Línea 25:             var settings = new MigrationsConfiguration();
Línea 26:             var migrator = new DbMigrator(settings);
Línea 27:             migrator.Update();
Línea 28:         }
Línea 29:     }

**Comment by Moantonio** [comment]
Uploading descarga.jpg.
Failed to upload descarga.jpg.
Debug Step by Step, handler == null, what is my error? 
need to configure?
![image](https://cloud.githubusercontent.com/assets/8619642/4292747/ee7fd44c-3dcf-11e4-8a46-7beee10ac705.png)
