### ISSUE TITLE
The number of unread messages isn't updating when I'm on jabber tab

### ISSUE THREAD

**Issue by luisrudge** [JabbR/JabbR#589]
When I leave the jabbr tab, the count of unread messages is updated accordingly, but when I return to the jabbr tab, the count isn't removed untill I switch rooms.

**Comment by samandmoore** [comment]
what browser are you using? there used to be a bug in chrome and we enacted
a work-around, but it was fixed in the last version so the work-around was
removed.

**Comment by luisrudge** [comment]
Oh, I'm running chrome 21.0.1180.89 on Windows 7 x64

**Comment by samandmoore** [comment]
hmm, i wonder if they broke it again. we can re-enact that fix if necessary.

**Comment by hnrkndrssn** [comment]
This is happening for me as well, switch away from Chrome, message count updates, switch back to Chrome read the messages in the room, count does not get cleared from Chrome Tab until I switch rooms.
Chrome Version 22.0.1229.94 m on Windows 8

**Comment by samandmoore** [comment]
this is the fix that was reverted. i will reimplement it 50e2a8a5aef7ab10742ea7f5cf498ad8ee32128c
