### ISSUE TITLE
Message box does not filter out style blocks, which messes up room styling for all connected users

### ISSUE THREAD

**Issue by JasonMore** [JabbR/JabbR#595]
We stumbled upon this today. You can put a _style_ block in the message box, and it affects all connected users:

![Bad Code](http://content.screencast.com/users/JasonMore/folders/Jing/media/5f268a8d-1c1a-41f6-8204-46ce54ede3b2/2012-10-02_0913.png)

![Broken Jabbr](http://content.screencast.com/users/JasonMore/folders/Jing/media/75c9d449-5173-4c41-ad5d-cd6bc0965e09/2012-10-02_0909.png)

The only way to fix it was I looked at the original style, then put the correct style back
![Good Code](http://content.screencast.com/users/JasonMore/folders/Jing/media/0d99a140-1286-40f5-b861-765a8940b01b/2012-10-02_0914.png)

Side note: github markdown sucks when it comes to showing style tag issues.

**Comment by danzel** [comment]
That's not all it doesn't filter.

Saying this will make a link that sends a message when clicked:

```
<a href="#" onclick="$('#new-message').val('hi'); $('#send').click(); return false">dontclick</a>
```

You can probably do something like

```
<img onload="evil js here" />
```

But I've already upset enough people, so I'm not testing that! :)

**Comment by danzel** [comment]
Introduced in db443b1b8ae025006de9d2fb89e51588c34cff64

Hubs/Chat.cs:139 (Send) encodes the message to be html escaped, then at line 164 calls in to ParseChatMessageText which calls TransformAndExtractUrls, which calls HtmlDecode on the message, resulting in the un-escaping.

**Comment by danzel** [comment]
Have sent a PR with a failing unit test, I'm not going to be able to fix this, that regex is way too hard.

**Comment by davidfowl** [comment]
This was fixed a while ago
