### ISSUE TITLE
Message content should not be stored HTML encoded

### ISSUE THREAD

**Issue by DamianEdwards** [JabbR/JabbR#597]
Message content is currently processed when received from a client (including HTML encoding it) and stored this way in the DB. This is poor design. User content should be stored in it's original state (or after scrubbed of invalid input via white-listing) and then HTML encoded before it is sent to the browser.

Due to the open XSS bug that was live on the site for a number of days, we now have hundreds of messages stored in the DB with the user generated portion _UNENCODED_. We can't update the code to just encode on the way out because all the other messages ever created are stored encoded, meaning they'd be double encoded.

**Comment by davidfowl** [comment]
Working on this.

**Comment by davidfowl** [comment]
Done.
