### ISSUE TITLE
cannot integrate JabbR with MVC Application

### ISSUE THREAD

**Issue by aburakab** [JabbR/JabbR#599]
I have two Projects; MVC 4 and JabbR (WebForms). I'm doing integration release, so I added JabbR as a reference in my MVC 4 Project. And I wrote batch file to copy all marckups to my project and bring the configurations, everything is great till now.

Now, I tried to run the app. But signalr/hubs is not available. i'm using IIS 8. Cannot detect the problem!!! Why!?

I also checked the FAQ in https://github.com/SignalR/SignalR/wiki/Faq

Nothing happend?!?!?! :( please help

**Comment by samandmoore** [comment]
JabbR is a standalone application. It is not meant to be integrated in the
way that you described above.

**Comment by aburakab** [comment]
Make sense, Opps I waste my time ... thanks a lot for your help. So now, If I want to use JabbR hub in my app ... everything that I need to do a reference for the hub. Right?

**Comment by vishal0909** [comment]
I have same problem. I need to implement JabbR in my MVC application like chat module. Is it possible to integration like facebook chat. 

Thanks and Regards
Vishal Kiri

**Comment by jrmcdona** [comment]
We have Jabbr integrated into our MVC app.   We have it done through iframe.  Works good and been working for several years.

**Comment by vishal0909** [comment]
can you please provide me some of code.
thanks and regards
vishal kiri



Sent from my Mi phone
On Jordan <notifications@github.com>, 22 Jun 2017 5:48 p.m. wrote:

We have Jabbr integrated into our MVC app. We have it done through iframe. Works good and been working for several years.

**Comment by jrmcdona** [comment]
Code to what?   Jabbr is the code.  You need to pull that down via GIT, and get it deployed somewhere.  We have ours deployed to Azure.

Then on our ASP.NET, MVC, Angular website we surface it through an iframe.  See below.  We pass a token from our web app to our jabbr app that helps with Auth.   BUt you should be able to get going with a few basics steps.

```

<div ng-if="isAmbassador && !nospecs">
    <div class="container">
        <div class="page-content-row">
            <div class="col-md-12" style="text-align: center;padding-top:25px;">
                <iframe ng-src="{{jabbrAzureUrl}}" id="" style="width:100%;height:700px;border:0px;"></iframe>
            </div>
        </div>
    </div>
</div>
```

**Comment by vishal0909** [comment]
Thanks for your quick reply.
I have my own chat ui and I need to implement Jabbr. I think it's work with iframe. I need to implement with Iframe.



Sent from my Mi phone
On Jordan <notifications@github.com>, 22 Jun 2017 6:48 p.m. wrote:

Code to what? Jabbr is the code. You need to pull that down via GIT, and get it deployed somewhere. We have ours deployed to Azure.

Then on our ASP.NET, MVC, Angular website we surface it through a URL. See below. We pass a token from our web app to our jabbr app that helps with Auth. BUt you should be able to get going with a few basics steps.


<div ng-if="isAmbassador && !nospecs">
    <div class="container">
        <div class="page-content-row">
            <div class="col-md-12" style="text-align: center;padding-top:25px;">
                <iframe ng-src="{{jabbrAzureUrl}}" id="" style="width:100%;height:700px;border:0px;"></iframe>
            </div>
        </div>
    </div>
</div>
