### ISSUE TITLE
Can not logon to jabbr

### ISSUE THREAD

**Issue by JasonMore** [JabbR/JabbR#614]
A friend of mine was trying to join a jabbr room I host, but he couldn't get on. So I did /logoff and tried to /login, and it looks like janrain is blocking any login attempts with this message:

JabbR Login
This application has been disabled.
switch accounts

![jabbr_login_fail](https://f.cloud.github.com/assets/383719/69276/a47af0c4-5f56-11e2-8e1b-cf5d63ad8568.png)

**Comment by heyvito** [comment]
Same problem here, but slightly different. It asks for a Twitter/Facebook/Google/OpenAuth account, and after providing the credentials and allowing the access, nothing happens.

**Comment by samandmoore** [comment]
You're both talking about hosting your own jabbrs right? You need to
configure janrain by registering on their website

**Comment by heyvito** [comment]
Hm, I was talking about JabbR.net. 
I tried again just now, the problem persists.

**Comment by JasonMore** [comment]
Jabbr.net for me as we'll

On Jan 16, 2013, at 6:46 AM, Victor Gama notifications@github.com wrote:

Hm, I was talking about JabbR.net.
I tried again just now, the problem persists.

—
Reply to this email directly or view it on
GitHubhttps://github.com/davidfowl/JabbR/issues/614#issuecomment-12316888.

**Comment by heyvito** [comment]
Maybe a problem with Janrain?

**Comment by JasonMore** [comment]
On Wed, Jan 16, 2013 at 7:46 AM, Victor Gama notifications@github.comwrote:

> Janrain

I think so. I have a feeling this happened to David:
http://blog.coredumped.org/2012/07/dont-trust-janrain-you-will-regret-it.html

**Comment by davidfowl** [comment]
Janrain has exceeded free accounts. @JasonMore they warned me but I'm going to replace the auth as soon as I can. For now only those who have their auth cookie can get back in.

**Comment by heyvito** [comment]
Make your own auth isn't an option?

**Comment by davidfowl** [comment]
That's what I mean by:

> I'm going to replace auth as soon as I can.

**Comment by TechnoTone** [comment]
I'm getting this too today. I was logging in fine yesterday using my Twitter account. Today, it says displays the above error message. :$

**Comment by Diullei** [comment]
i have the same problem.

**Comment by davidfowl** [comment]
Yes, everybody has the same problem.

**Comment by davidfowl** [comment]
This is fixed and jabbr is back!
