### ISSUE TITLE
render small images inline

### ISSUE THREAD

**Issue by adamralph** [JabbR/JabbR#683]
E.g. if I type

pull requested accepted https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/success-1348262443.png

Then it is rendered as 

pull request accepted ![](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/success-1348262443.png)

So long as the image is below a certain size, perhaps 32x32 max. If it is any bigger then it is rendered as currently, in a rich content box.

The image itself could be a hyperlink to the source image and/or show the URL in the tooltip.

It's important to consider what should happen loading history. I guess the default behaviour should probably match that of rich content boxes, i.e. inline images are not shown, just the URL's. Thanks to willl on JabbR for pointing that out.

**Comment by davidfowl** [comment]
That requires making a request to the resource to find out what the file size is. This isn't worth it.

**Comment by adamralph** [comment]
The image has to be requested at some point in order for it to be displayed. Can the decision for how to display it not be made at that point?

**Comment by davidfowl** [comment]
The user's browser handle's it which is very different from it happening on the server.

**Comment by davidfowl** [comment]
You could generate javascript to do it but I'm not sure that's worth the effort as I don't really see the benefit of this feature at all.

**Comment by adamralph** [comment]
The benefit is, effectively, unlimited emoticons. Not a necessary feature by all means, but would be a lot of fun :wink:.
