### ISSUE TITLE
Notification for directed messages window

### ISSUE THREAD

**Issue by fekberg** [JabbR/JabbR#684]
When someone writes your nick (@fekberg) and you're away from JabbR, there might be hundres of new messages making it hard to find the message.

My suggestion is that you have a way to see all these notifications (maybe in the Lobby?). Both private messages and directed messages (@).

**Comment by kiliman** [comment]
This is related to #752

**Comment by davidfowl** [comment]
This is being worked on. We're going to be adding ui for it as the db work is finished.

**Comment by cmaish** [comment]
I think that this can be closed now as there's a notifications page
