### ISSUE TITLE
AFK returns incorrect # of hours if server timezone is not UTC

### ISSUE THREAD

**Issue by cmaish** [JabbR/JabbR#688]
Using /afk on a machine that's at UTC-08:00 means that as soon as you go afk, the afk icon says "last seen 8 hours ago" immediately.  There's a similar effect on the /who command.

This seems to be because the UTC versions of dates are stored in the database, whereas the dates that come out are serialised as local dates before being sent to the client.

**Comment by cmaish** [comment]
Fix (potentially not ideal) at:

https://github.com/cmaish/JabbR/commit/4d9a2243eb0e3482afc11557665e5f3bf1d5ed41

**Comment by davidfowl** [comment]
Fixed
