### ISSUE TITLE
highlight my own username in username column of the channel history

### ISSUE THREAD

**Issue by adamralph** [JabbR/JabbR#692]
Sometimes when scrolling back through a long history, I want to find a conversation which I was involved in. This would be much easier if my username was highlighted in a different colour in the username column.

E.g.

![usernames](https://f.cloud.github.com/assets/677704/148783/cf124906-7511-11e2-8a25-5324664eb491.png)

**Comment by hnrkndrssn** [comment]
Fixed in b65fad35eabe4a2b8dc9516bb9c42fc95c557b40

**Comment by adamralph** [comment]
Awseome! Thanks.
