### ISSUE TITLE
Remove history after x items added to dom

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#694]
When leaving the client open for any extended period of time updates to the client are slow because history goes back probably 1000+ items.

My proposal is that after a certain level of inactivity the windows truncate the items in their views to a set number. say 500 and start truncating older entries. Scrolling should remain unaffected and it would increase performance when the window is open for a long time.

**Comment by davidfowl** [comment]
+1 :smile:

**Comment by samandmoore** [comment]
started a branch for this:

https://github.com/davidfowl/JabbR/compare/smoore;m;trim-history

**Comment by davidfowl** [comment]
@samandmoore sweet, how do you plan to handle the history loading?

**Comment by samandmoore** [comment]
I had a few thoughts.

I will pop into meta at some point to discuss.

Do we want to handle it on a per room basis? or just a global timer that
trims the room history at an interval?

**Comment by davidfowl** [comment]
Closing this
