### ISSUE TITLE
Windows authenticationmode never results in an authenticated user

### ISSUE THREAD

**Issue by christothes** [JabbR/JabbR#710]
I've configured Jabbr to run in an authenticationMode of "Windows". Although this results in being redirected to the windows login view, I am unable to authenticate (providing creds just results in being redirected to the login screen again).

As a side note, I was expecting that if the site was trusted, a secondary login would not be required, just like a basic out of the box ASP.Net site set to windows authentication mode.

**Comment by davidfowl** [comment]
Yea, that's because the feature isn't implemented.

**Comment by christothes** [comment]
Any pointers on where to start if I wanted to contribute the feature?

**Comment by davidfowl** [comment]
https://jabbr.net/#/rooms/meta is a good place to start

**Comment by davidfowl** [comment]
We're in here discussion it right now.

**Comment by christothes** [comment]
Anything come out of the discussion?

**Comment by davidfowl** [comment]
We're going to prioritize this.

**Comment by davidfowl** [comment]
@christothes let me know if it works for you.

**Comment by christothes** [comment]
I can't get it to work for me. I tried:
- adding back the authenticationMode application settings key back
- adding general authenitcation mode='windows' "

See my comment on the changeset.
[edit] I deleted the comment as it's no longer valid

**Comment by christothes** [comment]
This may be an IIS Express issue.. Checking that out now.

**Comment by christothes** [comment]
OK - it was a windows auth config issue on my side. Works great!
