### ISSUE TITLE
Flags in user list are overlapping names

### ISSUE THREAD

**Issue by Cheesebaron** [JabbR/JabbR#720]
![jabbrnetderrp](https://f.cloud.github.com/assets/249719/293728/53347380-93a8-11e2-9a37-7378bdae72fd.png)

As seen in the image above flags are positioned strangely in the user list. This occurs in Chrome Version 26.0.1410.40 beta-m, the other browsers I have installed are displaying it correctly. No other versions of Chrome have been tested.

Timestamp for deploy: Deployed from 40467ac49f on master at 22/03/2013 23:02.

**Comment by davidfowl** [comment]
I don't see this on my machine but I'm on Version 25.0.1364.172 m. Is it just chrome?

**Comment by Cheesebaron** [comment]
I have tried it in Firefox and IE and was not able to reproduce the problem there. So yes, this seems to be Chrome related.

**Comment by davidfowl** [comment]
Is that a dev build of chrome?

**Comment by Cheesebaron** [comment]
Beta.

**Comment by davidfowl** [comment]
@alfhenrik When you get a chance can you look at this in the beta version of chrome?

**Comment by hnrkndrssn** [comment]
yep, I'll do that this morning

Sent from my Windows Phone

**Comment by Cheesebaron** [comment]
I have played around with the `Stylish` plugin for Chrome and adding the following two lines to my CSS style for Jabbr.Net fixes the problem with the flags:

```
.flag {
  float: left;
  position: relative;
}
```

I would think the same would be applicable to the `.admin` class as well.

**Comment by hnrkndrssn** [comment]
I'll take a look at this tonight :) I had a quick play with it this morning and it seems to be working.
