### ISSUE TITLE
Unread message indicator in Browser tab does not clear when clicking tab

### ISSUE THREAD

**Issue by hnrkndrssn** [JabbR/JabbR#726]
The unread message indicator does get cleared if I alt+tab to my JabbR tab, but if I click my JabbR tab it does not get cleared.

Repro:
1. Select a different tab in your browser and wait for a message to arrive
2. Click your JabbR tab (unread messages is not cleared)
3. Clear the message by switching room tab in JabbR
4. Select a different tab in your browser and wait for a message to arrive
5. Alt+Tab to your JabbR tab (unread messages is cleared)

**Comment by samandmoore** [comment]
so, we made up a hack fix for this based on a chrome browser bug a long while back. then chrome fixed it, so i removed the hack. now it back.

**Comment by davidfowl** [comment]
@samandmoore can you find that fix and enable it. The setTimeout right?

**Comment by samandmoore** [comment]
yeah, here is a related issue:

https://github.com/davidfowl/JabbR/issues/589

**Comment by samandmoore** [comment]
and the commit hash of the fix. will add it back 

https://github.com/davidfowl/JabbR/commit/50e2a8a5aef7ab10742ea7f5cf498ad8ee32128c
