### ISSUE TITLE
don't display mis-typed commands in chat room

### ISSUE THREAD

**Issue by philchuang** [JabbR/JabbR#736]
feature-request: don't post invalid /commands to the chatroom.

Currently, when a command (anything prefixed with /) is typed and is not correct, it displays in the chat room.

This could be bad if people type /message instead of /msg and then their message is mistakenly made visible to the entire room.

**Comment by philchuang** [comment]
implemented : https://github.com/philchuang/JabbR/commit/3cd713c1e55517be970dbe4dcf5b670730daef7b

**Comment by davidfowl** [comment]
Fixed
