### ISSUE TITLE
Invalid password does not continue to redirectUrl

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#737]
Whenever you type an invalid password the returnUrl parameter is removed and you are no longer redirected to where you were intending to go.

**Comment by samandmoore** [comment]
You mean, once you submit the login form it loses the returnurl param? We can fix this.

**Comment by Buildstarted** [comment]
Yup

**Comment by cmaish** [comment]
Fixed in dev, should appear in prod soon.
