### ISSUE TITLE
Images in content provider links to image

### ISSUE THREAD

**Issue by Buildstarted** [JabbR/JabbR#739]
Requesting that you make images added to the chat via content providers actual links to the full images themselves

**Comment by davidfowl** [comment]
It already does. On jabbr.net it doesnt because it's SSL and it only proxies what isn't SSL which is everything. This is optional of course in jabbr the software.

**Comment by Buildstarted** [comment]
I don't understand what SSL has to do with linking the image. The images could be wrapped in an anchor tag is all i'm saying. Right now they're not. See pull request: https://github.com/davidfowl/JabbR/pull/743
