### ISSUE TITLE
Feature - #ShowShortcuts

### ISSUE THREAD

**Issue by coden4fun** [JabbR/JabbR#74]
Once typed in #ShowShortcuts it would display shortcuts only to that user (so it's not an inconvenience to the pros already familiar to the program)

**Comment by davidfowl** [comment]
No sure what you mean

**Comment by coden4fun** [comment]
OK, if you type in @dfowler you're specifically responding to that user thus that line highlights for that user.
if you type in /join roomname you join the room
if you type in create join/roomname (I forget the command forgive me) you can create the room
for code marks type in `code chunk`

Simply a link or a shortcut to display all the new features of what you can do with @ and # symbols and ways to join rooms.

For instance let's say i came back and I didn't know you added a way to join all rooms which would be /join all

I could go to the window and type in #ShowShortcuts and that would be a list of commands that I could use.

**Comment by davidfowl** [comment]
Isn't that what /help is for? Are you saying to extend /help

**Comment by coden4fun** [comment]
See, I didn't know /help was available.  lol #Fail

**Comment by kiliman** [comment]
There is a /help command. You are told about it in the Lobby. We should definitely update the help.

A lot of the features like auto-complete, highlighting, markup, and stuff were just recently added so not well documented.
