### ISSUE TITLE
Increase JabbR performance by creating appropriate indexes

### ISSUE THREAD

**Issue by kiliman** [JabbR/JabbR#751]
The performance for retrieving messages can be improved up to 50x by creating the correct index on the `ChatMessages` table.

Currently the only index is the `PK_ChatRooms` index on the auto-incrementing `Key` column. This is sub-optimal since all the queries for getting the most recent messages as well as for paging through previous messages query on the `When` column.

Here is the current execution plan for retrieving previous messages. Notice that the 99% of the query is spent on a Clustered Index Scan + sorting the results in reverse chronological order.

![beforeindex](https://f.cloud.github.com/assets/47168/308634/a843999e-96ed-11e2-9b20-7b67e4fc08d3.jpg)

We can also see that the I/O is pretty high, with 315 logical reads.

```
Table 'ChatRooms'. Scan count 1, logical reads 203, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'ChatMessages'. Scan count 1, logical reads 315, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
```

Now here is the same query after creating a proper clustered index on `When` column. Note that we are now doing a Clustered Index Seek and since the table is already sorted by `When`, the query plan no longer contains a sort step.

![afterindex](https://f.cloud.github.com/assets/47168/308636/ae5b8d46-96ed-11e2-91f1-2c3292e06fe9.jpg)

And the I/O has improved by 50x, with only 6 logical reads.

```
Table 'ChatRooms'. Scan count 1, logical reads 203, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'ChatMessages'. Scan count 1, logical reads 6, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
```

One thing to always consider when creating a clustered index is how this will affect inserts. Originally I was thinking that since all the queries are sorting by `When` in descending order, that it would be a good idea to create the clustered index the same way. However, this could cause issues as the actual inserts are in ascending order and will cause page splits constantly. It appears that SQL Server is smart enough to use the index properly despite the sorting being done in reverse.

Anyway, here is the SQL script for creating the proper clustered index. Note that I have to drop the original `PK_ChatMessages` so it will have to be done while JabbR is offline.

```
begin transaction
go

alter table dbo.ChatMessages drop constraint PK_ChatMessages
go

create clustered index CX_ChatMessages_When on dbo.ChatMessages ([When])
go

alter table dbo.ChatMessages add constraint PK_ChatMessages primary key nonclustered ([Key])
go

commit transaction
go
```

**Comment by davidfowl** [comment]
@kiliman why do we have to drop the PK constraint? How can we fit this into an EF migration?

**Comment by yeurch** [comment]
As you can only have one clustered index on a table, you must drop the PK first and recreate it as a non-clustered PK. This is because the new index on `When` is clustered.

**Comment by davidfowl** [comment]
Hmm I'm having some problems running this on sql azure:

```
Tables without a clustered index are not supported in this version of SQL Server. Please create a clustered index and try again.
Msg 3727, Level 16, State 0, Line 2
Could not drop constraint. See previous errors.
```

**Comment by yeurch** [comment]
Something like the following can do this in an EF migration.  Nor sure about Azure though. :(

```
using System.Data.Entity.Migrations;
using System;

public partial class ChangeIndexingOnChatMessages : DbMigration
{
    private static readonly string[] Statements = new[] {
        "alter table dbo.ChatMessages drop constraint PK_ChatMessages",
        "create clustered index CX_ChatMessages_When on dbo.ChatMessages ([When])",
        "alter table dbo.ChatMessages add constraint PK_ChatMessages primary key nonclustered ([Key])"
    };

    public override void Up()
    {
        foreach (var statement in Statements)
            Sql(statement);
    }

    public override void Down()
    {
        // Create a similar set of statements to reverse the index changes
    }
}
```

**Comment by davidfowl** [comment]
http://social.msdn.microsoft.com/Forums/en-US/ssdsgetstarted/thread/5cc4b302-fa42-4c62-956a-bbf79dbbd040

**Comment by yeurch** [comment]
Advice here is to create a new table and migrate the data across. Not good! http://social.msdn.microsoft.com/Forums/en-US/ssdsgetstarted/thread/5cc4b302-fa42-4c62-956a-bbf79dbbd040/

**Comment by yeurch** [comment]
Ah snap ... just found that too.

**Comment by kiliman** [comment]
Sorry that it's such a hassle to do on SQL Azure. I originally thought of using a standard index on When, but the query spent a lot of time doing key lookups to get the actual data rows. The other option was to include additional columns in the index itself which would ultimately mean duplicating the entire table in the index.

Anyway, seeing this is a one-time update, hopefully it's not too big a pain to do, because the performance improvement is totally worth it.

**Comment by davidfowl** [comment]
This is done on jabbr.net but not on jabbr the software. https://gist.github.com/davidfowl/5268953

I'm thinking of changing it so that the initial migration should contain these changes.

**Comment by onezerone** [comment]
JabbR is much faster with the new index! Sweet!
