### ISSUE TITLE
Adding persistent @Mentions support

### ISSUE THREAD

**Issue by kiliman** [JabbR/JabbR#752]
JabbR currently has support for notifying and highlighting message where the user's nick is @mentioned. However, this assumes the user is currently online and can view the notification. This is also the case when somebody `/msg` another user. This is only visible if the user is currently online, as they are not stored in the database.

I propose adding a persistent store for these type of messages. There are 2 types of messages (very similar to Twitter):
1. A private message (or DM) sent via the `/msg` command.
2. @mention when a user types the person's nick in a room

When a private message is sent or a message is typed in a room, we scan for any @mentions and create a `ChatMention` instance that includes the sender, recipient, message, and when. For the second type, we should also store the original `ChatMessage.Key` so we can reference the room and the message in context. This way the user can click on the @mention and jump to that message in the chat transcript.

We should also keep track of the last mention the user viewed, so we can identify how many new mentions the user received on subsequent login.

I'm also thinking that `/invite` should also be added, so perhaps we need to store the room as well.

I suppose there should be a way to delete private messages as well.

Anyway, what do you think of this feature? Anything I'm missing?

**Comment by davidfowl** [comment]
I started by adding basic mention support but nothing else as yet. The current plan is to copy the github ui for notifications.

**Comment by davidfowl** [comment]
Mention support is implemented. I think we're going to eventually nuke /msg and support proper 1 on 1 messages.
