### ISSUE TITLE
Loading history causing null ref.

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#771]
Saw this in general chat.

**Comment by hnrkndrssn** [comment]
Yes, it is occurring for me as well in meta...scroll up to the top, message says loading previous messages but they never load.

**Comment by samandmoore** [comment]
Hmm I didn't encounter that. Does it happen all the time or just if you
scroll up really fast? I've seen it when you scroll up really fast but that
was before the message trimming

**Comment by davidfowl** [comment]
Here's the real issue:

[02:00:48 GMT-0700 (PDT)] SignalR: getPreviousMessages.failed(general-chat, Object reference not set to an instance of an object.) 

So we just need to figure out what is null.

**Comment by davidfowl** [comment]
Ok this is my bug :smile: the generated client ids for messages should be replaced when the message comes back.

**Comment by davidfowl** [comment]
Fixed in https://github.com/davidfowl/JabbR/commit/bb10018d8dc4a38d3a5a4480bf64f37a3ae3ec83
