### ISSUE TITLE
Lobby modifications

### ISSUE THREAD

**Issue by hnrkndrssn** [JabbR/JabbR#781]
- [x] Room listed in wrong list, room that was not private was displayed in the Private Rooms list
- [x] Adding a new Private room (create new room, then lock it) does not move the room to the Private Rooms list
- [x] If you have no Private rooms the Other Rooms list should be renamed to Rooms
- [x] Speech bubble needs rework (too big)
- [x] Spacing of user details in the user list
- [x] Loading icon when sending message on a slow connection is screwy
- [x] Long names/topics in Private Room on the Lobby overflows the bounding box
- [x] Idle since time alignment is too high in relation to the rest of the details
- [x] On initially loading the lobby, instead of loading just the rooms that have users, load the first x number of rooms
- [x] Optimise room retrieval for the lobby, currently when we load the lobby we retrieve ALL the rooms, we should look at changing this to only retrieve a subset of the rooms and then when a users wants to load more rooms we go to the db and retrieve them.
- [x] Display a loading indicator when loading the lobby rooms list

**Comment by davidfowl** [comment]
This is done
