### ISSUE TITLE
Confirm navigate away/close browser tab

### ISSUE THREAD

**Issue by adamralph** [JabbR/JabbR#797]
Other web based chat clients throw up an 'Are you sure?' type dialog if you navigate away from their site or close the browser tab.

I've often closed my JabbR tab or clicked on a bookmark accidentally and I've found myself wanting this feature. It could also be made optional, toggled in the user settings.

**Comment by davidfowl** [comment]
I hate sites that do this so it'd have to be optional.

**Comment by adamralph** [comment]
Yeah, it's completely inappropriate for most sites that actually do it ;-).

However, JabbR and HipChat are two sites which I have open continuously and closing them is usually a mistake and very rarely an intention. HipChat has this feature but JabbR doesn't, and I miss it.

**Comment by samandmoore** [comment]
The thing is, you're not going to lose anything by closing jabbr. It makes
sense for something where you're in progress filling out a form. But not
for jabbr.

**Comment by adamralph** [comment]
There are a few things that are lost. E.g. indicators on room tabs where
I've been mentioned, direct messages, /me messages.

**Comment by samandmoore** [comment]
those are pieces of state that should be maintained by the app, not
concerns of the client. we have it in our roadmap to fix those issues
rather than add some sort of navigating away dialog

---

Sam Moore
908.625.1108
everywhere: samandmoore

**Comment by adamralph** [comment]
Ok that makes sense

**Comment by davidfowl** [comment]
+1 closing
