### ISSUE TITLE
Auto scroll to keep latest updates visible

### ISSUE THREAD

**Issue by sergevm** [JabbR/JabbR#8]
Don't know if it is intentional or not, but there is no scrolling into view of the latest updates. I think it would be nice to have an option to do so, such that you can work on some unrelated stuff while keeping an eye on what is happening in a room ...

**Comment by davidfowl** [comment]
Auto scroll happens if you are scrolled to the bottom. Can you give some more info on what you're using and what you did? e.g.
 What browser etc.

**Comment by sergevm** [comment]
Browser => Chrome 12.0.742.122 on a Windows XP box
Did nothing special, simply joined a room and watched. Under the impression that the first update scrolls down as expected, but after that you only see the scrollbar adjusting ...

**Comment by davidfowl** [comment]
It's working for me, not sure why that would be. I'm using chrome v13 on win7

**Comment by davidfowl** [comment]
Fixed in 610ca8d1b5f998edf06bd6a68fb7ddde99c83e8b
