### ISSUE TITLE
toast notification should say which room the message came from.

### ISSUE THREAD

**Issue by bxyoung** [JabbR/JabbR#808]
in chrome, the toast notifications should say which room a message came from.

**Comment by phillip-haydon** [comment]
Notifications say where the message came from. Which notification are you referring to?

**Comment by samandmoore** [comment]
this is already a thing

**Comment by davidfowl** [comment]
I think he means in chrome not the new notification feature

**Comment by samandmoore** [comment]
@davidfowl changed up and re-opened.

**Comment by bxyoung** [comment]
@davidfowl is correct - the chrome toast notification

**Comment by davidebbo** [comment]
And to add to this, it would be nice if clicking on the Chrome notification took you to the specific room that triggered the notification.

**Comment by davidfowl** [comment]
This is done.

**Comment by davidebbo** [comment]
Sweet!
