### ISSUE TITLE
Better private messaging

### ISSUE THREAD

**Issue by Cheesebaron** [JabbR/JabbR#812]
Would be awesome if when writing a /msg to a user a new tab would open with the conversation, such that it is not mixed in with the rest of the chat. Similar to what IRC does.

**Comment by damianh** [comment]
+1

**Comment by 0vermind** [comment]
+1

**Comment by ElanHasson** [comment]
+1

I created #1027 for message persistence.

**Comment by dpen2000** [comment]
I've started having a look at this.
I've got an initial implementation that has the /msg command create (or join if already exists) a unique private room for the two chatters involved. This approach gets this kind of private messaging working quite easily including message persistence (#1027). Does it seem reasonable?
Regardless of implementation, I'd expect a private messaging room/tab to have the following properties:
1. Be titled with the name of the user you've chatting with e.g. @dpen2000
2. Not have a list of users along the side
3. Allow users to enter and leave them without this showing in the chat history of the tab
4. If a person speaks in a private message tab or uses the /msg, the receiver of the message should have a private message tab auto appear in the background with an indicator (*) to show there is messages for them.
5. Should have persistent history of all previous private conversation between two chatters
6. Should probably disallow all or most commands as most won't make sense

**Comment by 0vermind** [comment]
I totally agree with the proposed implementation. 
I would add a way for the user to deny private messages in the options.
Looking forward to test it soon :)

**Comment by dpen2000** [comment]
cc: @davidfowl Thoughts?

**Comment by davidfowl** [comment]
Sounds great except that I would like to be able to deny a request for a private chat.

**Comment by hnrkndrssn** [comment]
We'll work on this in #194
