### ISSUE TITLE
Can't login via Twitter

### ISSUE THREAD

**Issue by peternavr** [JabbR/JabbR#828]
Method not found: 'System.Security.Principal.IIdentity Microsoft.Owin.Security.Forms.FormsResponseSignInContext.get_Identity()'.

Went to login tonight via Twitter and received this message.

**Comment by davidfowl** [comment]
Was broken now fixed.

**Comment by davidfowl** [comment]
Being worked on.

**Comment by davidfowl** [comment]
Fixed

**Comment by herecydev** [comment]
Still an issue for me; anything I'm missing?
