### ISSUE TITLE
DOM reflow issues when updating user lists

### ISSUE THREAD

**Issue by drub0y** [JabbR/JabbR#835]
During the DotNetConf today I noticed massive slowdown and, sometimes, outright hanging of IE as the room list grew. I profiled for a little bit and it appears that the sorting of the room user list ultimately causes O(N) calls to append which are forcing O(N) DOM reflows.

Here's a profiling screenshot where you can see how each call to addUser is ultimately calling addUserToList which ultimately calls sortList each time. If you drill in further (not shown in this screenshot) you'll see that the majority of the time there is attributable to the O(N) append calls that are occurring inside of sortList.

![JabbRAddUser_JavaScriptProfileTree](https://f.cloud.github.com/assets/284152/428275/170ce72e-ae02-11e2-8bdf-dba4b031964e.png)

A simple fix may just be to set the user list container element to display:none; prior to sorting. That could be potentially jarring depending on several layout factors, but worth a try in the short term.

If the display:none trick doesn't work, the child elements may need to be moved into a documentFragment before sorting and then moved back out into the live DOM after sorting has been completed.

**Comment by davidfowl** [comment]
This should be fixed now. We insert into the right place. If it comes back up as a performance issue we'll revisit.

**Comment by drub0y** [comment]
Yup, I haven't looked into the newer code or profiled it, but it has been performing much better since it was addressed.
