### ISSUE TITLE
Current tab isn't obvious: expected white to be the current tab, not gray

### ISSUE THREAD

**Issue by sidecut** [JabbR/JabbR#84]
The current highlighted tab is counter-intuitive: it's the gray tab when I would expect it to be the white tab.

This is an issue when there are only two tabs, e.g. Lobby and aspnet.

Everything else on the screen that's is active is colored white: the current room's chat window, the data entry area where I type my text, etc. Therefore one would expect the current tab to be white instead of gray.

**Comment by kiliman** [comment]
Yeah, this was my intial version of tabbed UI. Thanks for the feedback.

I'm also adding a close [x] icon on each tab to make it easy to leave rooms.

**Comment by sidecut** [comment]
Very nice feature. Consider it constructive criticism. :)

The close icon will be nice too.

**Comment by kiliman** [comment]
@dfowler did a makeover of JabbR, so the active tab color is very obvious. This can be closed.
