### ISSUE TITLE
Padlock Icon needs updating

### ISSUE THREAD

**Issue by phillip-haydon** [JabbR/JabbR#840]
The padlock icon is old and doesn't scale for Retina display. So all the icons look crystal clear except that one.

Need to replace it with a nice image that scales properly.

**Comment by hnrkndrssn** [comment]
We can convert it to use the icon-lock from FontAwesome, will scale nicely

**Comment by samandmoore** [comment]
Good call. I think I made that crummy icon. Please do remove it heh.
