### ISSUE TITLE
Joining a room with unicode characters in causes a syntax error in javascript, and the tabs fail to load

### ISSUE THREAD

**Issue by Yantrio** [JabbR/JabbR#842]
If you try to join room a room with Unicode characters for example (/join #강남스타일), then a javascript error is thrown and tabs are not loaded correctly.

"Uncaught Error: Syntax error, unrecognized expression: #tabs-_uAC15%uB0A8%uC2A4%uD0C0%uC77C JabbR1_817F36DAF3F0095B6B78764A3C7B052D.js:2"

the only way to resolve the logon issues is to logon, leave the room, and then re-log.

**Comment by cmaish** [comment]
This issue should be fixed by https://github.com/JabbR/JabbR/pull/846
