### ISSUE TITLE
run jabbr under Katana, throw exception

### ISSUE THREAD

**Issue by xgluxv** [JabbR/JabbR#844]
Run first get 500 error.
I found in NancyExtensions.cs file Line 89: module.Context.CurrentUser is null. this cause PrincialExtnsions.cs Line 51: “Claim claim = principal.FindFirst(type);” throw exception.

**Comment by davidfowl** [comment]
I couldn't reproduce this. I ran jabbr with owinhost.exe (katana.exe renamed) and i seemed to work well.
