### ISSUE TITLE
Incorrect encoding of < and > in source code of a github issue

### ISSUE THREAD

**Issue by SimonCropp** [JabbR/JabbR#850]
If a guthub issue is posted on Jabbr that has source code containing < or > they are incorrectly encoded as & lt; and & gt;  

For example:

```
<<<  >>>>

<script>alert('hello')</script>
```

<script>alert('hello')</script>

Post a link to this issue on Jabbr to see the problem

**Comment by davidfowl** [comment]
I updated this issue to have the xss case which caused us to add the over-encoding in the first place.
