### ISSUE TITLE
Save transcripts

### ISSUE THREAD

**Issue by joeriks** [JabbR/JabbR#86]
It would be nice to have some kind of "save transcript of this chat" feature, an option for the chat moderator (?) which would store all messages, to be avail later from an url like chatapp.apphb.com/razor/2011-11-16 

Saying this because I just attended a very informational chat and I'm sure I'm missing many interesting discussions each day :)

**Comment by davidfowl** [comment]
This is possible now through a rest api.

http://jabbr.net/api/v1/messages/meta

Will give you messages for the meta room. You can pass ?range=last-month/last-day/last-hour/all.
