### ISSUE TITLE
image file extension case sensitive

### ISSUE THREAD

**Issue by SimplyInfo** [JabbR/JabbR#866]
Image file extensions are case sensitive. IE: some news services use upper case file extensions and then the image does not show. Chat code only allows for lower case file extensions.

**Comment by cmaish** [comment]
Unable to repro.  We've altered a bunch of stuff around image handling, so it wouldn't surprise me if this is no longer an issue, but was this when you paste eg a BBC news link it doesn't show images in the content, or was it when you pasted an image url or something else?

Sounds like it could be an issue with http/https mixed mode and image proxying though...

**Comment by SimplyInfo** [comment]
It is any image file url where the image file extension is upper case. ie:
.jpg vs. .JPG
If you manually edit the url to a lower case version it will post the
image. If someone posts an image with the upper case file extension they
get a broken image.
I find it a minor annoyance but anyone new to the chat system gets
perplexed by the issue since they are not aware of how to get around it
unless someone familiar with the chat happens to be around to tell them or
fix the image for them.
When was the change to image handling updated?
I haven't pushed any updates to our chat site code since last year at some
point.

On Mon, Jul 22, 2013 at 2:54 PM, Chris Maish notifications@github.comwrote:

> Unable to repro. We've altered a bunch of stuff around image handling, so
> it wouldn't surprise me if this is no longer an issue, but was this when
> you paste eg a BBC news link it doesn't show images in the content, or was
> it when you pasted an image url or something else?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JabbR/JabbR/issues/866#issuecomment-21370924
> .

## 

_Nancy Foust_
www.SimplyInfo.org - The Fukushima Project
_Crowd sourced information research & analysis without focus on profit_
SimplyInfo.org research team member
SimplyInfo.org technical team member
info@simplyinfo.org - group email
lillymunster@gmail.com - Nancy's direct email
Blog - Going Green In A Red State http://houseoffoust.com/blog/

**Comment by cmaish** [comment]
OK, thanks for the quick reply.  If it's an issue with pasting eg http://mysite.com/image.JPG into the chat and not having it pick up that it's an image, I think that could have been fixed in January of this year with https://github.com/jabbr/jabbr/commit/9590191a4a686bab2c528f87a8f283997544467f#L0L27

This screenshot shows what it sounds was breaking in the past.  If that's not the case, feel free to reply and I'll reopen the issue.
![jabbr-uppercase-jpg](https://f.cloud.github.com/assets/1271535/837981/6e20266a-f313-11e2-950a-096cbca151bc.png)
