### ISSUE TITLE
Remove jquery-ui if possible

### ISSUE THREAD

**Issue by johnbfair** [JabbR/JabbR#873]
This is part 1 of a multi-part feature to get themeing into JabbR.  
1. Determine if the call to '.Add("~/Scripts/jquery-ui-1.10.0.min.js")' in \Views\Home\index.cshtml is truly necessary
   - If it is not necessary remove jquery-ui entirely
   - If it is necessary them leave it and create \Themes for housing the future theme files (separate issue)
2. Work on the next issue for project restructuring

**Comment by cmaish** [comment]
jQuery-UI appears to be used for the user nudge functionality so #885 has caused a minor regression (https://github.com/JabbR/JabbR/blob/master/JabbR/Chat.js#L655).  We should reimplement this ourselves.

**Comment by cmaish** [comment]
We can also revert the change to fix #689 as this was caused by jquery ui having different behavior with no argument in removeClass if we want now.

**Comment by johnbfair** [comment]
Ahhh nudge...we meet again.

Great catch @cmaish, and my apologies for breaking nudge w/ the removal of jQuery UI.  It appears we tested everything but nudge.  That's probably because we don't use nudge in our enterprise implementation at QL.  :frowning: 

I also agree that we should look at implementing nudge ourselves w/o jQuery UI.  @davidfowl how do you suggest we go about this?  Obviously a new issue, but would you like me to take the conn on that since our changes technically caused this issue?  Just let me know and I can get working on the fix ASAP.

**Comment by hnrkndrssn** [comment]
@cmaish raised https://github.com/JabbR/JabbR/issues/887 for the nudge issue so if you want you can fix that one :smiley:

**Comment by cmaish** [comment]
I think this can be closed.  We now have no jquery-ui in the project, and everything's sorted and seems to be working.
