### ISSUE TITLE
[OnPremise installation] Inconsistent access to an on-premise jabbr instance

### ISSUE THREAD

**Issue by mgrosperrin** [JabbR/JabbR#880]
Hi,

I've installed JabbR on a server in my company and I have some troubles :
for some PC, we can connect without any problems to JabbR and see all rooms,
but from some others PC we can't see rooms (but we can all access to jabbr.net).

After some investigations, I have discovered this strange thing :
the connect ajax call (to /signalr/connect), take 114s to respond and respond {"C":"B,2|By,0|Bz,1|B0,0","T":1,"M":[]} and all subsequent call do the same.
From my PC (where everything works), the connect ajax call is still running (with mode serverSendEvents);

**Comment by davidfowl** [comment]
Sounds like a proxy problem. What kind of network are those computers on?

**Comment by mgrosperrin** [comment]
Not sure to understand what you mean... We are on a private local network (not wifi).

If it is a proxy problem, we should not be able to use jabbr.net, right ?

**Comment by mgrosperrin** [comment]
In complement, here is a screenshot of what happens (or not in this case) after few minutes on the "lobby" page.

![screen1](https://f.cloud.github.com/assets/1014410/631141/cd504dee-d1bd-11e2-9728-a68ee3a4b93f.png)

**Comment by mgrosperrin** [comment]
One of my colleague has found a workaround (against my religion, but it works) :
when he is on the lobby, he change the compatibility mode of IE to IE7...

**Comment by davidfowl** [comment]
That sounds like proxy issues or some network device buffering. The reason jabbr.net works is because it's https.

**Comment by davidfowl** [comment]
The latest version should fall back appropriately.

**Comment by mgrosperrin** [comment]
Hi,

the last version (stable bt980) works !

Thanks for your time.
