### ISSUE TITLE
Need to update JabbR to use Twitter API 1.1 API

### ISSUE THREAD

**Issue by willl** [JabbR/JabbR#884]
Previously, if you pasted a tweet into any room in JabbR, it'll post the tweet inline.

But now that twitter has deprecated the 1.0 API, you get a bunch of javascript errors.

So if you paste the API call into your browser, you'll get the following message returned:
{"errors": [{"message": "The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.", "code": 68}]}

The twitter 1.0 API was officially retired on June 11th - https://dev.twitter.com/blog/api-v1-retirement-final-dates

**Comment by cmaish** [comment]
this can be closed now, right?

**Comment by willl** [comment]
@cmaish Yeah, I think so. It's been merged and AFAIK it works.
