### ISSUE TITLE
Nudge functionality is broken

### ISSUE THREAD

**Issue by cmaish** [JabbR/JabbR#887]
As a result of removing jquery-ui, nudge no longer causes the window move effect (in dev).  This is because there's a dependency at:

https://github.com/JabbR/JabbR/blob/master/JabbR/Chat.js#L655

We should reimplement this ourselves, jqui is too heavyweight and doesn't seem to be used elsewhere.

**Comment by cmaish** [comment]
There's a simple pulse implementation given in http://stackoverflow.com/questions/14934336/can-i-get-jquery-pulsate-effect-without-using-jquery-ui that we could adapt and use.

**Comment by johnbfair** [comment]
Great link @cmaish I think we could adapt that and do something similar.  Just want to get @davidfowl to weigh in on it and we can get a fix for this in soon.

**Comment by davidfowl** [comment]
What about https://github.com/jsoverson/jquery.pulse.js
