### ISSUE TITLE
Provide user status and flag in tooltip when mousing over name in chat log

### ISSUE THREAD

**Issue by devuxer** [JabbR/JabbR#888]
Feature request: When mousing over a name in the chat log, show a tooltip that contains the same information as in the room list. If the dots and flag images are not practical, even just a text version (e.g., "Available (USA)", "Idle 2h (Barbados)", or "Offline") would be very helpful.

If I read someone's question or statement, and I want to respond to it, this feature would make it a lot easier than searching through the room list to see whether the person is still online and will see my response.

**Comment by cmaish** [comment]
A small part of this has been done.  We have the user's status appearing next to the username in chat at current.

A popup that shows additional information about a user would be useful IMO on both the user list and when hovering over users in the message history.  This popup could initially have their name, status and idle time, but could be extended to incorporate gravatar info, notes etc.

**Comment by devuxer** [comment]
@cmaish, totally agree.

**Comment by hnrkndrssn** [comment]
I will do this together with #516 as they are working on the same parts of the application.
