### ISSUE TITLE
Submit IOS and Android Client 

### ISSUE THREAD

**Issue by zjinys** [JabbR/JabbR#896]
JabbR IOS and Android Client is develop by xamarin studio. Build it is not so easy , So how  about submit the client to store and other's can buy it.

**Comment by davidfowl** [comment]
When 2.0 is RTW there'll be a Xamarin component in the store for JabbR as well.

**Comment by zjinys** [comment]
You means in Xamarin store? I think a full feature client app in apple store or google play is more friend to end user. Why not server open source but mobile client is charged? At now JabbR is great . If there are good support with mobile client it will be more great.

**Comment by davidfowl** [comment]
There's no mobile client yet. It's being worked on but this is open source. If you want to work on it then have at it.

**Comment by DavePilks** [comment]
Has the Xamarin component been released yet? I cant seem to find it
