### ISSUE TITLE
Adding a Captcha to hinder bots

### ISSUE THREAD

**Issue by nschonni** [JabbR/JabbR#899]
There has already been some basic work done in #894, but @davidfowl pointed out that this may break the restful API.

Some thoughts:
1. Make it optional, but require some sort of account verification afterwards. Maybe allowing anyone to ban a user if they are not verified?
2. Require it anyways for a U/P combo, but allow it to be bypassed for OAuth logins/registrations

**Comment by cmaish** [comment]
This possibly could be implemented restfully using the noscript recaptcha API by requiring the user to include a captcha challenge IP and response in the message - roughly speaking the process could be:
- get a challenge, eg: http://www.google.com/recaptcha/api/challenge?k=6Lf4W-MSAAAAAC9AEdU_9cikGAznv5ldr2UVO2Oo
- whatever the consumer is shows the image, eg: http://www.google.com/recaptcha/api/image?c=03AHJ_VuufjmGU6UkKOx8VexrhlMCWQMkaUfLJ5wYgS7lo68mqHc00mtys2LKUHv0rFUzuY0GlZKdvljsGKDPI2WoQuohTMdxrlo6uqMPYMhdc9O1uqCHqi9r3ctGEsh_eyjiozmLJ-2temI8NeBVWvZJ2vbTsu9xllsres6QhAsD-p6g5azhx77I

When the user posts their creation request, they need to include the challenge and response fields which are pushed to the verify API (https://developers.google.com/recaptcha/docs/verify).

Of course, we need to actually implement this ourselves for the web interface, and make sure that it's permitted under google's TOS, but it could work.
