### ISSUE TITLE
Notifications view wrong Chinese display

### ISSUE THREAD

**Issue by zjinys** [JabbR/JabbR#902]
When Notification contained Chinese ,Not displayed correctly。 

![image](https://f.cloud.github.com/assets/66267/685169/a0018c5a-da1d-11e2-8a04-0dab9fc42c92.png)

Environment: Windows 2012/ SQL SERVER EXPRESS with default install , 

BTW: Chat message can show in right way.

**Comment by davidfowl** [comment]
Hmmm interesting.

**Comment by cmaish** [comment]
I think that this is fixed in the localisation PR.

I ran into something similar with NancyFx sending "text/html" as the content type header rather than "text/html; charset=utf-8"

https://github.com/JabbR/JabbR/pull/889/files#L60R78

**Comment by davidfowl** [comment]
@zjinys Does it only happen in chrome?

**Comment by davidfowl** [comment]
@cmaish btw setting the charset to utf8 fixes the problem in chrome.

**Comment by cmaish** [comment]
It's my guess that the first 1024 characters of the file or whatever each of the affected browsers use didn't contain characters that looked like UTF-8 so it got the character set wrong.  It wouldn't surprise me if this behavior was localised to a single browser based on each of them looking at the document in different ways to try to determine the encoding when there's no HTTP header, META or other bit of info specified.

**Comment by zjinys** [comment]
@davidfowl   Safari & IE10 & Firefox too. If I set the Text encoding to UTF-8 ,It will show the character correct.
