### ISSUE TITLE
Arrowkey-up loads last message, but upon editing it, resends the entire text

### ISSUE THREAD

**Issue by boxbinary** [JabbR/JabbR#91]
I guess I'm too used to Skype, whereup using arrowkey-up to load the last message and then editing the text would edit the message in the discussion rather than resending.

**Comment by davidfowl** [comment]
Are you saying that hitting another key besides enter sent your message?

**Comment by kiliman** [comment]
I think he means that he can choose a message from history and send it, and it'll be just another message in the chat (as if he typed it directly).

What it sounds like he wants is for the ability to resend a message and have it EDIT the existing message in chat. I'm not a big Skype user, so never tried it there. Seems kind of weird, especially if the message has already scrolled off the screen.

**Comment by davidfowl** [comment]
I don't like this feature :(
