### ISSUE TITLE
Tabs obscure room note when wrapped

### ISSUE THREAD

**Issue by jmkelly** [JabbR/JabbR#919]
In the new UI, when you have a large number of rooms open, once they wrap onto a second line the room note is partially obscured. Not sure how you would want to handle this, or even in fact if this is a real problem.

![image](https://f.cloud.github.com/assets/124026/728469/c80dd53c-e206-11e2-9cbb-35404bc521f9.png)

**Comment by davidfowl** [comment]
dupe of #138
