### ISSUE TITLE
JabbR.sln hangs Visual Studio 2012 when opened.

### ISSUE THREAD

**Issue by samkelleher** [JabbR/JabbR#925]
Tried on three different machines, all the same.  On opening, get prompted about SQL Express being updated to SQL Express 2012, then nothing happens - UI is frozen.  Although in the background, nuget.exe is continuously opening and closing itself. Any ideas?

Microsoft Visual Studio Ultimate 2012
Version 11.0.60610.01 Update 3
Microsoft .NET Framework
Version 4.5.50709

Installed Version: Ultimate

NuGet Package Manager   2.6.40627.9000
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

**Comment by samkelleher** [comment]
Removing this line from JabbR.csproj allows the solution to be opened, so I think this is related to the new version of nuget that updated recently?

```
<Import Project="$(SolutionDir)\.nuget\NuGet.targets" />
```

**Comment by gblmarquez** [comment]
I think it's the NuGet, last week when I opened the solution first I receive the same message but no freeze, everything just goes fine. 

BTW my version of NuGet is 2.5.40416.9020.

**Comment by davidfowl** [comment]
Should be fixed now.
