### ISSUE TITLE
misleading tab colours

### ISSUE THREAD

**Issue by adamralph** [JabbR/JabbR#931]
I think the current tab highlighting is misleading. The currently selected room is slightly darker grey than other tabs. Rooms with unseen messages are a very dark grey and are very distinctive.

If one room has an unseen message I keep thinking that is the room I'm in.

If many rooms have unseen messages it's difficult for me to pick out the currently active room.

I think the current active room should be very distinctive, and the rooms with unseen messages should have a more subtle shade. I would actually swap the current highlighting so that the currently active room gets the dark shade and the rooms with unseen messages get the slightly darker than normal shade.

**Comment by davidfowl** [comment]
@alfhenrik we need better contrast

**Comment by hnrkndrssn** [comment]
Fixed in 220dcb33277207c98fbae578562ffb0311c560ac
