### ISSUE TITLE
Windows Authentication - Not working - Infinite Loop

### ISSUE THREAD

**Issue by mattmhersh** [JabbR/JabbR#944]
Windows Authentication is not working. Receiving infinite loop in query string.

Steps to reproduce:
1. Disable Anonymous Authentication in IIS
2. Enable Windows Authentication
3. Browse to website.
4. Receive infinit loop issue in query string.

Troubleshooting:
1. Tried to see if Windows Principal is being passed by adding breakpoint on WindowsPrincipalHandler.cs. If you look at httpcontext.current you will see it is never making it to the invoke metod in the WindowsPrincipalHandler class.

Code: https://github.com/JabbR/JabbR/blob/master/JabbR/Middleware/WindowsPrincipalHandler.cs

Notes:
Seems like it is an issue with OWIN?

**Comment by kevinoconnor7** [comment]
+1 on this. It doesn't seem to be all the time though. I kept thinking it was an issue with my site configuration and redid my install a few times and was able to get it to successfully working once. However, I had to switch to anonymous auth to create an account and when I switched back I had this issue again.

**Comment by gyurisc** [comment]
I am seeing the same thing. Cannot enable windows authentication at the moment. It would be really nice though

**Comment by davidfowl** [comment]
Ok I think this is fixed now. Can somebody else verify that?

**Comment by gyurisc** [comment]
I will verify it on Monday in the office. Thanks for the fix @davidfowl , really appreciated!

**Comment by gyurisc** [comment]
I am still seeing this for some reason...

**Comment by davidfowl** [comment]
this is still broken

**Comment by davidfowl** [comment]
Ok this should be fixed now. I need somebody to verify it.

**Comment by davidfowl** [comment]
In the dev branch

**Comment by LRFalk01** [comment]
I'll check it out Monday morning. - Thanks.

**Comment by gyurisc** [comment]
@davidfowl  it seems to be working on my installation. Thanks for fixing it. Great stuff!

**Comment by LRFalk01** [comment]
Working for me as well.

**Comment by davidfowl** [comment]
Closing
