### ISSUE TITLE
Error on adding Google accounts where the name contains a hyphen

### ISSUE THREAD

**Issue by fatso83** [JabbR/JabbR#963]
There seems to be some kind of parsing error when constructing user names from real names. My registered given name in my google account is "Carl-Erik". This seems to have been converted to "Carl Erik", which apparently is illegal.

This all happened when I was trying to create a new account and pressed the Google button/link on the sign-in form.

![screen shot 2013-07-29 at 10 42 21](https://f.cloud.github.com/assets/618076/870380/5c48d49c-f82b-11e2-93d8-be1912f38b3c.png)

**Comment by chrisfcarroll** [comment]
jabbr.net still has this error as of today. I get "[InvalidOperationException: Chris F is not a valid user name.]" when attempting to sign up with google

**Comment by cmaish** [comment]
I don't think that a new deployment has been done just yet, so while this should be fixed when new builds are deployed, it'll probably take a couple of weeks before davidfowl gets around to pushing this change out.

**Comment by chrisfcarroll** [comment]
Noted, thanks.
