### ISSUE TITLE
Wrong messaging when adding someone to private room (screenshot)

### ISSUE THREAD

**Issue by DavidChristiansen** [JabbR/JabbR#969]
When adding someone to a room JabbR responds with 

```
You have been granted access to bryan_the_bot.
```

rather than something like

```
bryan_the_bot has been granted access to #roomname
```

![image](https://f.cloud.github.com/assets/77467/885676/7c0b0410-f9d6-11e2-9d62-6c84eb581228.png)

**Comment by cmaish** [comment]
Fix in dev branch, should find its way to prod soon.
