### ISSUE TITLE
Audible notifications for mentions only

### ISSUE THREAD

**Issue by thecodejunkie** [JabbR/JabbR#980]
It used to be that you only got audio notifications for @mentions, but these days it seems that you get them for all texts.

**Comment by jchannon** [comment]
Any update to this?

**Comment by hnrkndrssn** [comment]
I'm not sure anyone has looked into it.

But I'm pretty sure that I only get the audible notification when someone @mentions me on JabbR...

@thecodejunkie, does this issue still happen?

**Comment by thecodejunkie** [comment]
Pretty sure I only get it for @-mentions as well. Closing until proven wrong :P

**Comment by hnrkndrssn** [comment]
:grin:
