### ISSUE TITLE
Build Failing for master branch

### ISSUE THREAD

**Issue by ahirani** [JabbR/JabbR#987]
Can't not source the Nuget packages for Microsoft.Owin.*

**Comment by cmaish** [comment]
The underlying cause for this is that we are using the aspnet webstack nightlies which are only kept online for a short time.  We've updated to the latest nightlies, so the build should work again, but if we don't keep updating the signalr/owin version every few weeks, we will lose the ability to build from scratch again.

**Comment by davidfowl** [comment]
Yeah, I hate this shit... >_<. Need to move away from nightlies when 2.0 is released.

**Comment by ahirani** [comment]
Cheers Chris..

Understand your dilemma but on a positive note you are forced to always use
the latest version which hopefully should be more stable.

Will pull down master and have a look..

**Comment by ahirani** [comment]
Hey guys,

Still having issues building from master.

Can you try clean you packages folder then rebuild, should see what I get.

Thanks,

Neil

**Comment by davidfowl** [comment]
The issue isn't fixed in master. The fact that this bug is still open means we didnt fix anything.

**Comment by davidfowl** [comment]
Fixed
