### ISSUE TITLE
Facebook & Twitter Icons missing on login

### ISSUE THREAD

**Issue by peternavr** [JabbR/JabbR#990]
There is a small CSS bug where the rules are being overwritten.

http://i.imgur.com/HA8wDvK.png

**Comment by hnrkndrssn** [comment]
Works for me...
![image](https://f.cloud.github.com/assets/1035315/1161237/57fa0d22-1fe8-11e3-9c4d-111113b3114a.png)

What browser etc?

**Comment by peternavr** [comment]
Chrome (latest). But it seems to work on FireFox for me.

**Comment by hnrkndrssn** [comment]
I tested in the following:
Chrome: Version 29.0.1547.66 m
Internet Explorer: 9.0.8112.16421
Firefox: 23.0.1 and 24.0

And it all works as expected, so not sure why your Chrome doesn't work...
